# GENERATED by scripts/sync-sdk-python.sh from sdk/python/tests/_async/test_component_files.py by unasync — do not edit.
"""vms.files: stat (HEAD), download (GET, checked against Content-Length) and upload (PUT, a body
of known size) on /api/vms/{name}/files, over a MockTransport (mirrored by unasync).

The wire rules come from the contract (sdk/openapi.yaml): the ``path`` query is percent-encoded
and a ``+`` means a literal ``+``; an upload needs a ``Content-Length``; a download body shorter
than its ``Content-Length`` is a failed download.
"""

import io
from collections.abc import Iterator, Callable
from datetime import datetime, timezone

import httpx
import pytest
from mockapi import HEADERS

from cove_sdk import (
    CoveAPIError,
    CoveError,
    DownloadTruncatedError,
    FileNotRegularError,
    FilePathDeniedError,
    FileTooLargeError,
    NotFoundError,
    PayloadTooLargeError,
    PermissionDeniedError,
    ServerError,
    UnavailableError,
    ValidationError,
    VmFileNotFoundError,
    VmFileStat,
)
from cove_sdk._sync._transport import SyncCoveTransport
from cove_sdk._sync.resources.vms import Vms
from cove_sdk.auth import BearerAuth
from cove_sdk.types import FileUploaded

UPLOADED = {"path": "/root/a b.txt", "size": 6, "mode": 420, "sha256": "ab" * 32}


def _vms(
    handler: Callable[[httpx.Request], httpx.Response],
) -> tuple[list[httpx.Request], Vms]:
    seen: list[httpx.Request] = []

    def record(request: httpx.Request) -> httpx.Response:
        seen.append(request)
        return handler(request)

    t = SyncCoveTransport(
        "https://h", auth=BearerAuth("cvk_t"), transport=httpx.MockTransport(record)
    )
    return seen, Vms(t)


def _file(
    content: bytes, *, size: int | None = None, mode: str | None = "0644"
) -> Callable[[httpx.Request], httpx.Response]:
    def handler(request: httpx.Request) -> httpx.Response:
        headers = {
            **HEADERS,
            "content-length": str(len(content) if size is None else size),
        }
        if mode is not None:
            headers["x-cove-file-mode"] = mode
        body = b"" if request.method == "HEAD" else content
        return httpx.Response(200, headers=headers, content=body)

    return handler


def _error(status: int, code: str | None) -> Callable[[httpx.Request], httpx.Response]:
    def handler(request: httpx.Request) -> httpx.Response:
        if code is None:
            return httpx.Response(status, headers=HEADERS)
        return httpx.Response(
            status, headers=HEADERS, json={"code": code, "message": "m"}
        )

    return handler


def _ok(request: httpx.Request) -> httpx.Response:
    return httpx.Response(200, headers=HEADERS, json=UPLOADED)


# -- the request line ------------------------------------------------------------------------------


def test_component_files_path_query_encodes_space_as_percent20_and_keeps_plus() -> None:
    seen, vms = _vms(_file(b"", size=0))
    vms.files.stat("my vm", "/root/a b+c&d=é.txt")
    url = seen[0].url
    assert url.raw_path == (
        b"/api/vms/my%20vm/files?path=%2Froot%2Fa%20b%2Bc%26d%3D%C3%A9.txt"
    )


def test_component_files_a_path_with_a_lone_surrogate_is_a_cove_error() -> None:
    seen, vms = _vms(_ok)
    with pytest.raises(CoveError, match="Unicode"):
        vms.files.stat("v", "/a\ud800")
    with pytest.raises(CoveError, match="Unicode"):
        vms.files.upload("v", "/a\ud800", b"x")
    assert seen == []


def test_component_files_name_is_a_guarded_path_segment() -> None:
    seen, vms = _vms(_ok)
    for bad in ("", ".", ".."):
        with pytest.raises(CoveError):
            vms.files.stat(bad, "/a")
        with pytest.raises(CoveError):
            vms.files.download_bytes(bad, "/a")
        with pytest.raises(CoveError):
            vms.files.upload(bad, "/a", b"x")
    assert seen == []


# -- stat ----------------------------------------------------------------------------------------


def test_component_files_stat_sends_head_and_reads_size_and_mode() -> None:
    seen, vms = _vms(_file(b"", size=1234, mode="0755"))
    st = vms.files.stat("v", "/usr/bin/tool")
    assert seen[0].method == "HEAD"
    assert st == VmFileStat(size=1234, mode=0o755)


def test_component_files_stat_mode_is_none_without_the_header() -> None:
    _, vms = _vms(_file(b"abc", mode=None))
    assert vms.files.stat("v", "/a") == VmFileStat(size=3, mode=None)


def test_component_files_stat_reads_mtime_from_last_modified() -> None:
    def handler(request: httpx.Request) -> httpx.Response:
        headers = {
            **HEADERS,
            "content-length": "3",
            "last-modified": "Tue, 14 Nov 2023 22:13:20 GMT",
        }
        return httpx.Response(200, headers=headers)

    _, vms = _vms(handler)
    st = vms.files.stat("v", "/a")
    assert st.mtime == datetime(2023, 11, 14, 22, 13, 20, tzinfo=timezone.utc)
    assert st.mtime is not None and st.mtime.tzinfo is not None


def test_component_files_stat_mtime_is_none_without_a_readable_last_modified() -> None:
    # An older server sends no Last-Modified; a garbled one is not a date.
    for last_modified in (None, "not a date"):

        def handler(
            request: httpx.Request, lm: str | None = last_modified
        ) -> httpx.Response:
            headers = {**HEADERS, "content-length": "3"}
            if lm is not None:
                headers["last-modified"] = lm
            return httpx.Response(200, headers=headers)

        _, vms = _vms(handler)
        assert (vms.files.stat("v", "/a")).mtime is None, last_modified


def test_component_files_stat_errors_take_their_code_from_x_cove_error_code() -> None:
    # A HEAD error has no body; the server names its code in a header, so a missing VM and a
    # missing file, or a denied path and a missing scope, are told apart.
    cases: list[tuple[int, str, type[CoveAPIError]]] = [
        (404, "vm_not_found", NotFoundError),
        (404, "file_not_found", VmFileNotFoundError),
        (403, "file_path_denied", FilePathDeniedError),
        (403, "scope_denied", PermissionDeniedError),
        (413, "file_too_large", FileTooLargeError),
    ]
    for status, code, cls in cases:

        def handler(
            request: httpx.Request, status: int = status, code: str = code
        ) -> httpx.Response:
            return httpx.Response(
                status, headers={**HEADERS, "x-cove-error-code": code}
            )

        _, vms = _vms(handler)
        with pytest.raises(cls) as info:
            vms.files.stat("v", "/a")
        assert type(info.value) is cls, (status, code)
        assert (info.value.status, info.value.code) == (status, code)


def test_component_files_stat_refuses_a_200_without_content_length() -> None:
    def handler(request: httpx.Request) -> httpx.Response:
        response = httpx.Response(200, headers=HEADERS)
        assert "content-length" not in response.headers
        return response

    _, vms = _vms(handler)
    with pytest.raises(CoveError, match="Content-Length"):
        vms.files.stat("v", "/a")


def test_component_files_stat_errors_have_no_body_so_the_status_names_the_class() -> (
    None
):
    # A loop, not parametrize: conftest marks coroutine tests for anyio at collection.
    cases: list[tuple[int, type[CoveAPIError], str | None]] = [
        (413, FileTooLargeError, "file_too_large"),
        (422, FileNotRegularError, "file_not_regular"),
        (503, UnavailableError, "unavailable"),
        # 403 is a deny-listed path OR a key without files:read; 404 a missing VM OR a missing
        # file. Neither can be told apart without a body.
        (403, PermissionDeniedError, None),
        (404, NotFoundError, None),
    ]
    for status, cls, code in cases:
        _, vms = _vms(_error(status, None))
        with pytest.raises(cls) as info:
            vms.files.stat("v", "/a")
        assert type(info.value) is cls
        assert (info.value.status, info.value.code) == (status, code)


# -- download ------------------------------------------------------------------------------------


def test_component_files_download_streams_the_body_with_size_and_mode() -> None:
    seen, vms = _vms(_file(b"heyyou", mode="0600"))
    download = vms.files.download("v", "/etc/motd")
    assert seen == []  # nothing is sent until the block is entered
    with download as dl:
        assert (dl.size, dl.mode) == (6, 0o600)
        chunks = [c for c in dl]
    assert b"".join(chunks) == b"heyyou"
    assert seen[0].method == "GET"
    assert seen[0].headers["accept"] == "application/octet-stream"
    assert seen[0].headers["accept-encoding"] == "identity"


def test_component_files_download_reads_mtime_from_last_modified() -> None:
    def handler(request: httpx.Request) -> httpx.Response:
        headers = {
            **HEADERS,
            "content-length": "1",
            "last-modified": "Tue, 14 Nov 2023 22:13:20 GMT",
        }
        return httpx.Response(200, headers=headers, content=b"x")

    _, vms = _vms(handler)
    with vms.files.download("v", "/a") as dl:
        assert dl.mtime == datetime(2023, 11, 14, 22, 13, 20, tzinfo=timezone.utc)


def test_component_files_a_content_encoded_download_is_refused_not_miscounted() -> None:
    def handler(request: httpx.Request) -> httpx.Response:
        headers = {**HEADERS, "content-length": "1", "content-encoding": "br"}
        return httpx.Response(200, headers=headers, content=b"x")

    _, vms = _vms(handler)
    with pytest.raises(CoveError, match="Content-Encoding br"):
        vms.files.download_bytes("v", "/a")


def test_component_files_download_bytes_returns_the_whole_file() -> None:
    _, vms = _vms(_file(b"abcde"))
    assert vms.files.download_bytes("v", "/a") == b"abcde"


def test_component_files_download_bytes_of_an_empty_file_is_empty() -> None:
    _, vms = _vms(_file(b""))
    assert vms.files.download_bytes("v", "/empty") == b""


def test_component_files_a_body_shorter_than_content_length_is_a_failed_download() -> (
    None
):
    _, vms = _vms(_file(b"abc", size=10))
    with pytest.raises(DownloadTruncatedError) as info:
        vms.files.download_bytes("v", "/a")
    assert (info.value.expected_bytes, info.value.received_bytes) == (10, 3)
    assert isinstance(info.value, CoveError)


def test_component_files_a_body_longer_than_content_length_is_refused() -> None:
    _, vms = _vms(_file(b"abcdef", size=2))
    with pytest.raises(DownloadTruncatedError):
        vms.files.download_bytes("v", "/a")

    # The stream form raises before any byte past Content-Length reaches the caller, who may
    # already be writing the chunks to a sink.
    _, vms = _vms(_file(b"abcdef", size=2))
    yielded = b""
    with vms.files.download("v", "/a") as dl:
        with pytest.raises(DownloadTruncatedError):
            for chunk in dl:
                yielded += chunk
    assert len(yielded) <= 2


def test_component_files_a_connection_lost_mid_body_is_a_failed_download() -> None:
    class Broken(httpx.SyncByteStream):
        def __iter__(self) -> Iterator[bytes]:
            yield b"abc"
            raise httpx.RemoteProtocolError("peer closed connection")

    def handler(request: httpx.Request) -> httpx.Response:
        return httpx.Response(
            200, headers={**HEADERS, "content-length": "10"}, stream=Broken()
        )

    _, vms = _vms(handler)
    with pytest.raises(DownloadTruncatedError) as info:
        vms.files.download_bytes("v", "/a")
    assert info.value.received_bytes == 3
    assert isinstance(info.value.__cause__, httpx.RemoteProtocolError)


def test_component_files_download_must_be_iterated_inside_its_block() -> None:
    _, vms = _vms(_file(b"abc"))
    download = vms.files.download("v", "/a")
    with pytest.raises(CoveError, match="with block"):
        download.__iter__()


def test_component_files_download_errors_map_to_file_error_classes() -> None:
    cases: list[tuple[int, str, type[CoveAPIError]]] = [
        (413, "file_too_large", FileTooLargeError),
        (403, "file_path_denied", FilePathDeniedError),
        (403, "scope_denied", PermissionDeniedError),
        (422, "file_not_regular", FileNotRegularError),
        (404, "file_not_found", VmFileNotFoundError),
        (404, "vm_not_found", NotFoundError),
        (503, "unavailable", UnavailableError),
    ]
    for status, code, cls in cases:
        _, vms = _vms(_error(status, code))
        with pytest.raises(cls) as info:
            vms.files.download_bytes("v", "/a")
        assert type(info.value) is cls
        assert info.value.code == code


def test_component_files_error_classes_extend_their_status_class() -> None:
    assert issubclass(FileTooLargeError, PayloadTooLargeError)
    assert issubclass(FilePathDeniedError, PermissionDeniedError)
    assert issubclass(FileNotRegularError, ValidationError)
    assert issubclass(VmFileNotFoundError, NotFoundError)
    assert issubclass(UnavailableError, ServerError)


# -- upload --------------------------------------------------------------------------------------


def test_component_files_upload_puts_bytes_and_returns_the_commit() -> None:
    seen, vms = _vms(_ok)
    out = vms.files.upload("v", "/root/a b.txt", b"heyyou")
    req = seen[0]
    assert req.method == "PUT"
    assert req.url.raw_path == b"/api/vms/v/files?path=%2Froot%2Fa%20b.txt"
    assert req.headers["content-type"] == "application/octet-stream"
    assert req.headers["content-length"] == "6"
    assert req.content == b"heyyou"
    assert isinstance(out, FileUploaded)
    assert (out.path, out.size, out.mode) == ("/root/a b.txt", 6, 420)


def test_component_files_upload_accepts_str_bytearray_and_memoryview() -> None:
    for data in ("héllo", bytearray("héllo".encode()), memoryview("héllo".encode())):
        seen, vms = _vms(_ok)
        vms.files.upload("v", "/a", data)
        assert seen[0].content == "héllo".encode()
        assert seen[0].headers["content-length"] == str(len("héllo".encode()))


def test_component_files_upload_mode_is_sent_as_four_octal_digits() -> None:
    cases: list[tuple[int | str, str]] = [
        (0o755, "0755"),
        (0o4, "0004"),
        ("0600", "0600"),
    ]
    for mode, wire in cases:
        seen, vms = _vms(_ok)
        vms.files.upload("v", "/a", b"x", mode=mode)
        assert (
            seen[0].url.raw_path == f"/api/vms/v/files?path=%2Fa&mode={wire}".encode()
        )


def test_component_files_upload_refuses_a_mode_outside_0777() -> None:
    for mode in (0o1000, -1, True, "rwx", "01777"):
        seen, vms = _vms(_ok)
        with pytest.raises(CoveError, match="mode"):
            vms.files.upload("v", "/a", b"x", mode=mode)
        assert seen == []


def test_component_files_upload_reads_a_file_object_from_its_position() -> None:
    seen, vms = _vms(_ok)
    f = io.BytesIO(b"skip:heyyou")
    f.seek(5)
    vms.files.upload("v", "/a", f)
    assert seen[0].headers["content-length"] == "6"
    assert seen[0].content == b"heyyou"


def test_component_files_upload_streams_an_iterator_with_its_size() -> None:
    def chunks() -> Iterator[bytes]:
        yield b"hey"
        yield b"you"

    seen, vms = _vms(_ok)
    vms.files.upload("v", "/a", chunks(), size=6)
    assert seen[0].headers["content-length"] == "6"
    assert "transfer-encoding" not in seen[0].headers
    assert seen[0].content == b"heyyou"


def test_component_files_an_iterator_upload_needs_a_size() -> None:
    def chunks() -> Iterator[bytes]:
        yield b"x"

    seen, vms = _vms(_ok)
    with pytest.raises(CoveError, match="size"):
        vms.files.upload("v", "/a", chunks())
    assert seen == []


def test_component_files_an_iterator_that_does_not_match_its_size_fails() -> None:
    for parts, size in (([b"abc"], 6), ([b"abcdefgh"], 6)):

        def chunks(parts: list[bytes] = parts) -> Iterator[bytes]:
            for p in parts:
                yield p

        _, vms = _vms(_ok)
        with pytest.raises(CoveError, match="declared size"):
            vms.files.upload("v", "/a", chunks(), size=size)


class _Committing(httpx.BaseTransport):
    """A server that, like cove, reads an upload only up to its ``Content-Length`` and commits the
    file the moment it has every byte. Not a MockTransport, which reads the whole request body
    before its handler runs and so would drain a body past its ``Content-Length`` first."""

    def __init__(self) -> None:
        self.commits: list[bytes] = []
        self.requests = 0

    def handle_request(self, request: httpx.Request) -> httpx.Response:
        self.requests += 1
        expected = int(request.headers["content-length"])
        received = b""
        if expected:
            for chunk in request.stream:  # type: ignore[union-attr]
                received += chunk
                if len(received) >= expected:
                    break
        if len(received) < expected:
            return httpx.Response(400, headers=HEADERS, json={"code": "short_body"})
        self.commits.append(received[:expected])
        return httpx.Response(200, headers=HEADERS, json=UPLOADED)


def _committing() -> tuple[_Committing, Vms]:
    server = _Committing()
    t = SyncCoveTransport("https://h", auth=BearerAuth("cvk_t"), transport=server)
    return server, Vms(t)


class _Pieces:
    """A file object that cannot seek and returns one preset piece per ``read``, as a pipe or a
    socket can."""

    def __init__(self, pieces: list[bytes]) -> None:
        self._pieces = list(pieces)

    def read(self, n: int = -1) -> bytes:
        return self._pieces.pop(0) if self._pieces else b""

    def seekable(self) -> bool:
        return False


def test_component_files_a_body_past_its_size_at_a_chunk_boundary_is_never_committed() -> (
    None
):
    # b"hey" + b"you" is exactly 6 bytes: a body that sent b"you" before looking for more would
    # hand the server a whole file it commits, and the b"!" past it could no longer fail it.
    pieces = [b"hey", b"you", b"!"]

    def chunks() -> Iterator[bytes]:
        for p in pieces:
            yield p

    for data in (chunks(), _Pieces(pieces)):
        server, vms = _committing()
        with pytest.raises(
            CoveError, match=r"declared size of 6 bytes \(it ran past it\)"
        ):
            vms.files.upload("v", "/a", data, size=6)  # type: ignore[arg-type]
        assert server.commits == []


def test_component_files_a_body_declared_empty_that_yields_bytes_is_refused_unsent() -> (
    None
):
    # With Content-Length: 0 the headers alone are the whole file.
    def chunks() -> Iterator[bytes]:
        yield b""
        yield b"x"

    for data in (chunks(), _Pieces([b"x"])):
        server, vms = _committing()
        with pytest.raises(CoveError, match="declared size of 0 bytes"):
            vms.files.upload("v", "/a", data, size=0)  # type: ignore[arg-type]
        assert (server.commits, server.requests) == ([], 0)

    # A body that really is empty uploads an empty file.
    server, vms = _committing()
    vms.files.upload("v", "/a", _Pieces([]), size=0)  # type: ignore[arg-type]
    assert server.commits == [b""]


def test_component_files_a_body_matching_its_size_is_committed_whole() -> None:
    # The control for the two tests above: the held-back final chunk is sent.
    def chunks() -> Iterator[bytes]:
        for p in (b"hey", b"", b"you"):
            yield p

    for data in (chunks(), _Pieces([b"hey", b"you"])):
        server, vms = _committing()
        vms.files.upload("v", "/a", data, size=6)  # type: ignore[arg-type]
        assert server.commits == [b"heyyou"]


def test_component_files_a_size_that_contradicts_a_sized_body_is_refused() -> None:
    seen, vms = _vms(_ok)
    with pytest.raises(CoveError, match="size"):
        vms.files.upload("v", "/a", b"abc", size=4)
    with pytest.raises(CoveError, match="size"):
        vms.files.upload("v", "/a", b"abc", size=-1)
    assert seen == []


def test_component_files_upload_errors_are_typed() -> None:
    def handler(request: httpx.Request) -> httpx.Response:
        return httpx.Response(
            413,
            headers=HEADERS,
            json={"code": "file_too_large", "message": "over the 1 GiB limit"},
        )

    _, vms = _vms(handler)
    with pytest.raises(FileTooLargeError, match="1 GiB"):
        vms.files.upload("v", "/a", b"x")
