# GENERATED by scripts/sync-sdk-python.sh from sdk/python/tests/_async/test_component_sharing_meta.py by unasync — do not edit.
"""VM sharing, meta.users() and meta.openapi() round-trips (mirrored to the sync client by unasync)."""

import pytest
from mockapi import Api

from cove_sdk._sync._transport import SyncCoveTransport
from cove_sdk._sync.resources.meta import Meta
from cove_sdk._sync.resources.vms import Vms
from cove_sdk._generated.models import (
    GrantShareOutcome,
    RevokeShareOutcome,
    SharedVmSummary,
    ShareEntry,
)
from cove_sdk.auth import BearerAuth
from cove_sdk.errors import CoveError

SHARE = {
    "granted_at": "2026-10-01T00:00:00Z",
    "granted_by": "alice",
    "role": "collaborator",
    "subject_id": "eng",
    "subject_type": "team",
}


def _t(api: Api) -> SyncCoveTransport:
    return SyncCoveTransport(
        "https://h", auth=BearerAuth("cvk_t"), transport=api.transport()
    )


def test_component_vms_sharing_round_trips() -> None:
    api = (
        Api()
        .on(
            "GET",
            "/api/vms/shared-with-me",
            (
                200,
                [
                    {
                        "image": "fedora-43",
                        "name": "w",
                        "owner": "bob",
                        "state": "running",
                    }
                ],
            ),
        )
        .on("GET", "/api/vms/v/access", (200, [SHARE]))
        .on("POST", "/api/vms/v/access", (201, {"user_known": False}))
        .on("DELETE", "/api/vms/v/access/team/eng", (200, {"revoked": True}))
    )
    vms = Vms(_t(api))
    shared = vms.shared_with_me()
    assert isinstance(shared[0], SharedVmSummary)
    assert (shared[0].name, shared[0].owner) == ("w", "bob")
    access = vms.access("v")
    assert isinstance(access[0], ShareEntry) and access[0].subject_id == "eng"
    granted = vms.share("v", subject_type="team", subject_id="eng", role="collaborator")
    assert (api.last.method, api.last_json()) == (
        "POST",
        {"subject_type": "team", "subject_id": "eng", "role": "collaborator"},
    )
    assert isinstance(granted, GrantShareOutcome) and granted.user_known is False
    revoked = vms.unshare("v", "team", "eng")
    assert (api.last.method, api.last.url.path) == (
        "DELETE",
        "/api/vms/v/access/team/eng",
    )
    assert isinstance(revoked, RevokeShareOutcome) and revoked.revoked is True


def test_component_vms_unshare_guards_all_three_segments() -> None:
    api = Api()
    vms = Vms(_t(api))
    for args in (("..", "user", "bob"), ("v", ".", "bob"), ("v", "user", "..")):
        with pytest.raises(CoveError):
            vms.unshare(*args)
    with pytest.raises(CoveError):
        vms.access("..")
    with pytest.raises(CoveError):
        vms.share("", subject_type="user", subject_id="bob", role="user")
    assert api.seen == []


def test_component_vms_unshare_encodes_each_segment() -> None:
    api = Api().on("DELETE", "/api/vms/v/access/user/a%2Fb", (200, {"revoked": False}))
    out = Vms(_t(api)).unshare("v", "user", "a/b")
    assert out.revoked is False


def test_component_meta_users_and_openapi() -> None:
    doc = {
        "openapi": "3.1.0",
        "info": {"title": "cove", "version": "5"},
        "paths": {"/api/vms": {"get": {"operationId": "listVms"}}},
    }
    api = (
        Api()
        .on("GET", "/api/users", (200, ["alice", "bob"]))
        .on("GET", "/api/openapi.json", (200, doc))
    )
    meta = Meta(_t(api))
    assert meta.users() == ["alice", "bob"]
    got = meta.openapi()
    assert type(got) is dict
    assert got == doc
    assert got["paths"]["/api/vms"]["get"]["operationId"] == "listVms"
