# GENERATED by scripts/sync-sdk-python.sh from sdk/python/tests/_async/test_unit_sse.py by unasync — do not edit.
"""The SSE parser and its bounded line splitter (mirrored to the sync layer by unasync)."""

from collections.abc import Iterator, Iterable

import pytest

from cove_sdk._sync._sse import MAX_SSE_BYTES, ServerSentEvent, iter_lines, parse_sse
from cove_sdk.errors import CoveError


def _chunks(parts: Iterable[bytes]) -> Iterator[bytes]:
    for part in parts:
        yield part


def _events(parts: Iterable[bytes]) -> list[ServerSentEvent]:
    return [e for e in parse_sse(iter_lines(_chunks(parts)))]


def _lines(parts: Iterable[bytes]) -> list[str]:
    return [line for line in iter_lines(_chunks(parts))]


def test_unit_sse_named_event_and_default_message() -> None:
    events = _events([b"event: stdout\ndata: hi\n\ndata: plain\n\n"])
    assert events == [
        ServerSentEvent("stdout", "hi", None),
        ServerSentEvent("message", "plain", None),
    ]


def test_unit_sse_comments_are_ignored() -> None:
    events = _events([b": keep-alive\n\n:another\nevent: x\n: mid\ndata: y\n\n"])
    assert events == [ServerSentEvent("x", "y", None)]


def test_unit_sse_strips_exactly_one_leading_space() -> None:
    events = _events([b"data:  two\n\ndata:none\n\n"])
    assert [e.data for e in events] == [" two", "none"]


def test_unit_sse_multiline_data_joined_with_newline() -> None:
    events = _events([b"event: stdout\ndata: a\ndata:\ndata: b\n\n"])
    assert events == [ServerSentEvent("stdout", "a\n\nb", None)]


def test_unit_sse_id_field_is_carried() -> None:
    events = _events([b"event: lifecycle\nid: 42\ndata: {}\n\n"])
    assert events == [ServerSentEvent("lifecycle", "{}", "42")]


def test_unit_sse_every_line_ending() -> None:
    # A loop, not parametrize: conftest marks coroutine tests for anyio at collection.
    for eol in (b"\n", b"\r\n", b"\r"):
        raw = eol.join([b"event: a", b"data: 1", b"", b"data: 2", b"", b""])
        assert _events([raw]) == [
            ServerSentEvent("a", "1", None),
            ServerSentEvent("message", "2", None),
        ], eol


def test_unit_sse_crlf_split_across_chunks_is_one_line_end() -> None:
    assert _lines([b"a\r", b"\nb\r\n"]) == ["a", "b"]


def test_unit_sse_utf8_split_across_chunks() -> None:
    raw = "data: é€\n\n".encode()
    assert _events([raw[:7], raw[7:]]) == [ServerSentEvent("message", "é€", None)]


def test_unit_sse_event_split_at_every_byte_offset() -> None:
    raw = b'event: stdout\r\ndata: one\r\n\r\nevent: exit\ndata: {"code":0}\n\n'
    want = [
        ServerSentEvent("stdout", "one", None),
        ServerSentEvent("exit", '{"code":0}', None),
    ]
    for i in range(len(raw) + 1):
        for j in range(i, len(raw) + 1):
            assert _events([raw[:i], raw[i:j], raw[j:]]) == want, (i, j)


def test_unit_sse_unterminated_final_event_is_dispatched() -> None:
    # As sse.ts does: a stream cut after the last field still yields what it carried.
    assert _events([b"event: exit\ndata: {}"]) == [ServerSentEvent("exit", "{}", None)]


def test_unit_sse_line_cap_raises_before_buffering_past_one_chunk() -> None:
    chunk = 64 * 1024
    pulled = 0

    def endless() -> Iterator[bytes]:
        nonlocal pulled
        # A newline-free stream, bounded at twice the cap so a missing cap fails, not hangs.
        while pulled < 2 * MAX_SSE_BYTES:
            pulled += chunk
            yield b"x" * chunk

    with pytest.raises(CoveError, match="SSE line exceeded 16 MiB"):
        for _ in iter_lines(endless()):
            pass
    assert MAX_SSE_BYTES < pulled <= MAX_SSE_BYTES + chunk


def test_unit_sse_line_cap_counts_a_terminated_line_too() -> None:
    with pytest.raises(CoveError, match="SSE line exceeded"):
        _lines([b"x" * (MAX_SSE_BYTES + 1) + b"\n"])
    # positive control: a line of exactly the cap passes
    assert [len(x) for x in _lines([b"x" * MAX_SSE_BYTES + b"\n"])] == [MAX_SSE_BYTES]


def test_unit_sse_event_data_cap() -> None:
    line = b"data: " + b"x" * (4 * 2**20) + b"\n"
    with pytest.raises(CoveError, match="SSE event exceeded 16 MiB"):
        _events([line] * 5)
    # positive control: the same lines in separate events pass
    assert len(_events([line + b"\n"] * 5)) == 5


def test_unit_sse_small_cap_is_honoured() -> None:
    with pytest.raises(CoveError, match="SSE line exceeded"):
        for _ in iter_lines(_chunks([b"abcdef"]), cap=4):
            pass
    with pytest.raises(CoveError, match="SSE event exceeded"):
        for _ in parse_sse(iter_lines(_chunks([b"data: abc\ndata: d\n\n"])), cap=4):
            pass


def test_unit_sse_closing_the_parser_closes_its_source() -> None:
    closed = []

    def source() -> Iterator[bytes]:
        try:
            while True:
                yield b"data: x\n\n"
        finally:
            closed.append(True)

    events = parse_sse(iter_lines(source()))
    for _ in events:
        break
    events.close()
    assert closed == [True]


def test_unit_sse_lone_lf_chunk_after_cr_clears_the_pending_crlf() -> None:
    # The "\n" completing a CRLF arrives alone; the next chunk's leading "\n" is a real blank line.
    assert _events([b"data: a\r", b"\n", b"\ndata: b\n\n"]) == [
        ServerSentEvent("message", "a", None),
        ServerSentEvent("message", "b", None),
    ]


def test_unit_sse_empty_chunk_keeps_the_pending_crlf() -> None:
    # An empty chunk carries nothing, so the "\n" after it still completes the CRLF.
    assert _lines([b"a\r", b"", b"\nb\n"]) == ["a", "b"]


def test_unit_sse_every_three_way_split_matches_one_chunk() -> None:
    raw = b"data: a\r\n\ndata: b\r\r\n\ndata: c\n\r\ndata: d\r\n\r\n"
    want = _events([raw])
    assert [e.data for e in want] == ["a", "b", "c", "d"]  # positive control
    for i in range(len(raw) + 1):
        for j in range(i, len(raw) + 1):
            for k in range(j, len(raw) + 1):
                parts = [raw[:i], raw[i:j], raw[j:k], raw[k:]]
                assert _events(parts) == want, (i, j, k)
