"""Write the Python SDK's generated public parts (run by scripts/sync-sdk-python.sh).

    gen_types.py --meta <openapi.yaml>          -> _meta.py on stdout (API_VERSION from info.version)
    gen_types.py <generated-pkg> <openapi.yaml> -> types.py on stdout

types.py re-exports the generated models under an explicit, sorted ``__all__`` that leaves out
every anonymous-branch name (``<Schema>Type<n>`` and anything nested under it), and exposes each
``oneOf`` schema under its own name as a ``Union``: the ``<Schema>Type<n>`` classes the generator
emitted for inline branches, or the referenced classes and aliases for ``$ref`` branches. The
generated model list comes from ``<generated-pkg>/models/__init__.py``'s ``__all__`` (parsed, never
imported); the ``oneOf`` schemas from the contract's ``components.schemas``. The contract is read,
never rewritten. Any inconsistency (a missing branch class, a name collision, a ``$ref`` to a schema
with no model) exits non-zero: a wrong ``types.py`` must never be written quietly.
"""

from __future__ import annotations

import ast
import pathlib
import re
import sys
from typing import Any, NoReturn

from ruamel.yaml import YAML
from ruamel.yaml.error import YAMLError

ANONYMOUS = re.compile(r"Type\d+")
HEADER = '"""GENERATED by scripts/sync-sdk-python.sh — do not edit."""'


def die(msg: str) -> NoReturn:
    print(f"gen_types: {msg}", file=sys.stderr)
    sys.exit(1)


def load_contract(path: str) -> dict[str, Any]:
    try:
        with open(path, encoding="utf-8") as f:
            doc = YAML(typ="safe").load(f)
    # A parse error must stop the sync, never default anything.
    except (OSError, YAMLError) as e:
        die(f"cannot read {path}: {e}")
    if not isinstance(doc, dict):
        die(f"{path} is not a YAML mapping")
    return doc


def meta(path: str) -> str:
    info = load_contract(path).get("info")
    if not isinstance(info, dict):
        die(f"{path} has no top-level info: block")
    if "version" not in info:
        die(f"{path} has no info.version")
    version = str(info["version"])
    if not re.fullmatch(r"[0-9]+", version):
        die(f"{path} info.version {version!r} is not an integer")
    return (
        '"""GENERATED by scripts/sync-sdk-python.sh from sdk/openapi.yaml info.version — do not edit."""\n'
        "\n"
        f"API_VERSION: int = {int(version)}\n"
    )


def generated_models(pkg: pathlib.Path) -> list[str]:
    init = pkg / "models" / "__init__.py"
    try:
        tree = ast.parse(init.read_text(encoding="utf-8"))
    except OSError as e:
        die(f"cannot read {init}: {e}")
    for node in tree.body:
        if isinstance(node, ast.Assign) and any(
            isinstance(t, ast.Name) and t.id == "__all__" for t in node.targets
        ):
            names = ast.literal_eval(node.value)
            if not names or not all(isinstance(n, str) for n in names):
                die(f"{init}: __all__ is empty or not a sequence of names")
            return list(names)
    die(f"{init} has no __all__")


def ref_name(ref: str) -> str:
    prefix = "#/components/schemas/"
    if not ref.startswith(prefix):
        die(f"unsupported $ref {ref!r} (only {prefix}<Name> is handled)")
    return ref[len(prefix) :]


def types_py(pkg: pathlib.Path, contract: str) -> str:
    models = generated_models(pkg)
    model_set = set(models)
    if len(model_set) != len(models):
        die("the generated models' __all__ lists a name twice")
    exported = sorted(n for n in models if not ANONYMOUS.search(n))

    schemas = load_contract(contract).get("components", {}).get("schemas", {})
    if not isinstance(schemas, dict) or not schemas:
        die(f"{contract} has no components.schemas")
    unions: dict[str, list[tuple[str, str]]] = {}  # name -> [(kind, target)]
    for name, schema in schemas.items():
        if not isinstance(schema, dict) or "oneOf" not in schema:
            continue
        if ANONYMOUS.search(name):
            die(
                f"oneOf schema {name} has a name the anonymous-branch filter would drop"
            )
        branches: list[tuple[str, str]] = []
        for i, branch in enumerate(schema["oneOf"]):
            if isinstance(branch, dict) and "$ref" in branch:
                branches.append(("ref", ref_name(branch["$ref"])))
            else:
                cls = f"{name}Type{i}"
                if cls not in model_set:
                    die(
                        f"oneOf {name} branch {i} is inline but the generator emitted no {cls}"
                    )
                branches.append(("branch", cls))
        unions[name] = branches

    collisions = sorted(set(exported) & set(unions))
    if collisions:
        die(f"a union alias collides with a generated model: {', '.join(collisions)}")

    # Aliases may reference other aliases (VmConflictResponse -> DenyReason): emit in dependency order.
    order: list[str] = []
    state: dict[str, str] = {}

    def visit(n: str) -> None:
        if state.get(n) == "done":
            return
        if state.get(n) == "active":
            die(f"oneOf schemas reference each other in a cycle through {n}")
        state[n] = "active"
        for kind, target in unions[n]:
            if kind == "ref":
                if target in unions:
                    visit(target)
                elif target not in model_set or ANONYMOUS.search(target):
                    die(
                        f"oneOf {n} references {target}, which has no exported generated model"
                    )
        state[n] = "done"
        order.append(n)

    for n in sorted(unions):
        visit(n)

    public = sorted(set(exported) | set(unions))
    lines = [
        HEADER,
        "",
        "import typing as _t",
        "",
        "from ._generated import models as _models",
        "from ._generated.models import (",
        *(f"    {n}," for n in exported),
        ")",
        "",
    ]
    for n in order:
        members = []
        for kind, target in unions[n]:
            if kind == "branch":
                members.append(f"_models.{target}")
            else:
                members.append(target)
        lines.append(f"{n}: _t.TypeAlias = _t.Union[{', '.join(members)}]")
    lines += ["", "__all__ = [", *(f'    "{n}",' for n in public), "]", ""]
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    if len(argv) == 2 and argv[0] == "--meta":
        sys.stdout.write(meta(argv[1]))
        return 0
    if len(argv) == 2:
        sys.stdout.write(types_py(pathlib.Path(argv[0]), argv[1]))
        return 0
    print(
        "usage: gen_types.py --meta <openapi.yaml> | <generated-pkg> <openapi.yaml>",
        file=sys.stderr,
    )
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
