"""Mirror the hand-written async code into its generated sync twin (run by scripts/sync-sdk-python.sh).

    run_unasync.py <package-dir> <out-dir>

reads ``<package-dir>/src/cove_sdk/_async/**.py`` and ``<package-dir>/tests/_async/**.py`` and
writes their unasync translations to ``<out-dir>/src/cove_sdk/_sync/`` and ``<out-dir>/tests/_sync/``
(the sync script diffs or copies them from there). Every mirrored file starts with a header naming
its source. unasync 0.6.0 replaces whole NAME tokens (and the same names inside strings); the table
below adds what its defaults miss. Hand-written ``_async/`` code annotates context managers with
``contextlib.AbstractAsyncContextManager``, never ``typing.AsyncContextManager`` (which would
mirror to a ``SyncContextManager`` that does not exist). Later slices may add entries, and only
entries; the mirrored tests are what catch a missing one.
"""

from __future__ import annotations

import os
import pathlib
import sys

import unasync  # type: ignore[import-untyped]  # unasync 0.6.0 ships no py.typed

REPLACEMENTS = {
    "aclose": "close",
    "aread": "read",
    "aiter_bytes": "iter_bytes",
    "aiter": "iter",
    "AsyncCoveClient": "CoveClient",
    "AsyncClient": "Client",
    "AsyncBaseTransport": "BaseTransport",
    "AsyncHTTPTransport": "HTTPTransport",
    "asyncio_detailed": "sync_detailed",
    "asyncio": "sync",
    "async_sleep": "sync_sleep",
    "async_read_chunk": "sync_read_chunk",
    "async_run_blocking": "sync_run_blocking",
    "_async": "_sync",
    "set_async_httpx_client": "set_httpx_client",
    "get_async_httpx_client": "get_httpx_client",
    "AbstractAsyncContextManager": "AbstractContextManager",
    "AsyncByteStream": "SyncByteStream",
    "handle_async_request": "handle_request",
}

# (source dir under the package, mirror dir under the output), relative paths.
TREES = (
    ("src/cove_sdk/_async", "src/cove_sdk/_sync"),
    ("tests/_async", "tests/_sync"),
)


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print("usage: run_unasync.py <package-dir> <out-dir>", file=sys.stderr)
        return 2
    pkg, out = (pathlib.Path(a).resolve() for a in argv)
    for src_rel, dst_rel in TREES:
        src = pkg / src_rel
        dst = out / dst_rel
        files = sorted(
            str(p) for p in src.rglob("*.py") if "__pycache__" not in p.parts
        )
        if not files:
            print(
                f"run_unasync: {src} holds no .py files (at least __init__.py is expected)",
                file=sys.stderr,
            )
            return 1
        rule = unasync.Rule(
            fromdir=str(src) + os.sep,
            todir=str(dst) + os.sep,
            additional_replacements=REPLACEMENTS,
        )
        unasync.unasync_files(files, rules=[rule])
        for f in files:
            rel = pathlib.Path(f).relative_to(src)
            mirrored = dst / rel
            if not mirrored.is_file():
                print(
                    f"run_unasync: unasync wrote no {mirrored} for {f}", file=sys.stderr
                )
                return 1
            body = mirrored.read_text(encoding="utf-8")
            header = (
                f"# GENERATED by scripts/sync-sdk-python.sh from sdk/python/{src_rel}/{rel.as_posix()}"
                " by unasync — do not edit.\n"
            )
            mirrored.write_text(header + body, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
