# GENERATED by scripts/sync-sdk-python.sh from sdk/python/src/cove_sdk/_async/resources/admin.py by unasync — do not edit.
"""``client.admin``: every ``/api/admin`` operation -- the fleet, the host, projects, quotas, users,
every VM and every checkpoint.

Each method needs an administrator and the ``admin:*`` scope its docstring names (bare ``admin``
satisfies them all). An API key reaches them only if it is an admin key, minted with
``cove key create --admin`` (``admin_key: true``, short-lived), whose owner is in the server's
``[auth] admins``; an ordinary or pre-upgrade key holding the scope gets 403 ``admin_required``
(:class:`~cove_sdk.PermissionDeniedError`). Every listener serves them (over a bearer key, only
to an admin key of an ``[auth] admins`` user), except :meth:`Admin.drain_host`, which the
Warpgate-fronted listener never serves.

Seven of them refuse every API key, an admin key included, with 401 ``sudo_required``.
:meth:`Admin.update_vm_agents`, :meth:`Admin.bulk_stop_vms`, :meth:`Admin.bulk_delete_vms`,
:meth:`Admin.delete_checkpoint`, :meth:`Admin.offboard_user` and :meth:`Admin.enable_user` need a
recent interactive sign-in, so they run only with a ticket
or a session, never a key. :meth:`Admin.drain_host` is never served on the Warpgate-fronted
listener either, so in practice it runs on the host's Unix socket.
"""

from __future__ import annotations

import builtins
from collections.abc import Iterator, Mapping
from typing import Any, BinaryIO, cast

from ..._args import build_body, opt
from ..._generated.api.admin import (
    bulk_delete_vms,
    bulk_stop_vms,
    create_project_member,
    create_quota_bypass,
    delete_any_checkpoint,
    delete_project_member,
    delete_team_quota_override,
    delete_user_quota_override,
    drain_host,
    get_host_state,
    get_quota_defaults,
    get_team_quota_override,
    get_user,
    get_user_quota_override,
    list_all_users,
    list_all_vms,
    list_any_checkpoints,
    enable_user,
    list_project_members,
    offboard_user,
    revoke_user_sessions,
    update_auto_pause_timeouts,
    update_team_quota_override,
    update_user_quota_override,
    update_vm_agents,
)
from ..._generated.models import (
    AdminBulkVmRequest,
    AdminBulkVmResponse,
    AdminCheckpointSummary,
    AdminCheckpointSummaryPage,
    AdminDrainResponse,
    AdminForceCreateResponse,
    AdminHostStateResponse,
    AdminProjectMemberRequest,
    AdminQuotaDefaultsResponse,
    AdminQuotaOverrideRequest,
    AdminQuotaOverrideResponse,
    AdminRetimeoutRequest,
    AdminRetimeoutResponse,
    AdminTeamQuotaOverrideRequest,
    AdminTeamQuotaOverrideResponse,
    AdminUserSummary,
    AdminVmSummary,
    AdminVmSummaryPage,
    EnableUserResponse,
    OffboardUserReport,
    OffboardUserRequest,
    ProjectMember,
    RevokeSessionsResponse,
    UpdateAgentsResponse,
)
from ..._generated.types import File
from ..._operations import operation
from .._pagination import paginate
from .._transport import CLIENT_DEFAULT, SyncCoveTransport, CallTimeout


class Admin:
    """``client.admin`` — administrator operations. Every one needs an administrator."""

    def __init__(self, transport: SyncCoveTransport) -> None:
        self._t = transport

    # -- the fleet and the host --------------------------------------------------------------

    @operation("updateAutoPauseTimeouts")
    def update_auto_pause_timeouts(
        self,
        body: AdminRetimeoutRequest | Mapping[str, Any] | None = None,
        *,
        timeout: CallTimeout = CLIENT_DEFAULT,
        **fields: Any,
    ) -> AdminRetimeoutResponse:
        """Move auto-pausing VMs to a new idle timeout (``from_secs``, ``to_secs``, ``dry_run``).

        ``by_current_value`` maps each current timeout, in seconds written as a string, to how
        many VMs have it. It comes back as the generated mapping model
        (``AdminRetimeoutResponseByCurrentValue``); its ``.to_dict()`` is that map as a plain
        ``dict[str, int]``. Scope ``admin:fleet:write``.
        """
        req = build_body(AdminRetimeoutRequest, body, fields)
        out = self._t.call(update_auto_pause_timeouts, body=req, timeout=timeout)
        return cast(AdminRetimeoutResponse, out)

    @operation("drainHost")
    def drain_host(
        self,
        *,
        budget_secs: int | None = None,
        timeout: CallTimeout = CLIENT_DEFAULT,
    ) -> AdminDrainResponse:
        """Stop every running and paused VM on the host, every tenant's, within ``budget_secs``.

        Disks survive; there is no dry run. Scope ``admin:fleet:write``.

        Never served on the Warpgate-fronted listener, and it refuses every API key, an admin key
        included, with 401 ``sudo_required``: in practice a drain runs on the host's Unix socket.
        """
        out = self._t.call(drain_host, budget_secs=opt(budget_secs), timeout=timeout)
        return cast(AdminDrainResponse, out)

    @operation("getHostState")
    def host_state(
        self, *, timeout: CallTimeout = CLIENT_DEFAULT
    ) -> AdminHostStateResponse:
        """The host's gauges: pending expiries, audit-write failures, snapshot images, orphans.

        Scope ``admin:host:read``.
        """
        out = self._t.call(get_host_state, timeout=timeout)
        return cast(AdminHostStateResponse, out)

    @operation("updateVmAgents")
    def update_vm_agents(
        self, binary: bytes, *, timeout: CallTimeout = CLIENT_DEFAULT
    ) -> UpdateAgentsResponse:
        """Push a new guest-agent binary to every running VM; ``binary`` is sent as is.

        Scope ``admin:agent-push``.

        Refuses every API key, an admin key included, with 401 ``sudo_required``: it needs a
        ticket or a session.
        """
        # The generated call hands File.payload to httpx as the request content. Raw bytes serve
        # both clients; a BytesIO is a sync stream, which an async httpx client refuses to send.
        payload = File(
            payload=cast(BinaryIO, bytes(binary)), mime_type="application/octet-stream"
        )
        out = self._t.call(update_vm_agents, body=payload, timeout=timeout)
        return cast(UpdateAgentsResponse, out)

    @operation("bulkDeleteVms")
    def bulk_delete_vms(
        self,
        body: AdminBulkVmRequest | Mapping[str, Any] | None = None,
        *,
        timeout: CallTimeout = CLIENT_DEFAULT,
        **fields: Any,
    ) -> AdminBulkVmResponse:
        """Delete VMs by ``scope`` (``{"type": "all"}``, ``{"type": "user", "username": ...}`` or
        ``{"type": "vms", "vm_names": [...]}``), with ``dry_run`` and ``include_pool``.

        Scope ``admin:fleet:delete``.

        Refuses every API key, an admin key included, with 401 ``sudo_required``: it needs a
        ticket or a session.
        """
        req = build_body(AdminBulkVmRequest, body, fields)
        out = self._t.call(bulk_delete_vms, body=req, timeout=timeout)
        return cast(AdminBulkVmResponse, out)

    @operation("bulkStopVms")
    def bulk_stop_vms(
        self,
        body: AdminBulkVmRequest | Mapping[str, Any] | None = None,
        *,
        timeout: CallTimeout = CLIENT_DEFAULT,
        **fields: Any,
    ) -> AdminBulkVmResponse:
        """Stop VMs by ``scope``, as :meth:`bulk_delete_vms`. Scope ``admin:fleet:write``.

        Refuses every API key, an admin key included, with 401 ``sudo_required``: it needs a
        ticket or a session.
        """
        req = build_body(AdminBulkVmRequest, body, fields)
        out = self._t.call(bulk_stop_vms, body=req, timeout=timeout)
        return cast(AdminBulkVmResponse, out)

    # -- projects ----------------------------------------------------------------------------

    @operation("listProjectMembers")
    def list_project_members(
        self, project_id: str, *, timeout: CallTimeout = CLIENT_DEFAULT
    ) -> builtins.list[ProjectMember]:
        """Who belongs to project ``project_id``. Scope ``admin:projects:read``."""
        out = self._t.call(
            list_project_members, path={"project_id": project_id}, timeout=timeout
        )
        return cast(builtins.list[ProjectMember], out)

    @operation("createProjectMember")
    def add_project_member(
        self, project_id: str, username: str, *, timeout: CallTimeout = CLIENT_DEFAULT
    ) -> None:
        """Add ``username`` to project ``project_id``. Scope ``admin:projects:write``."""
        req = AdminProjectMemberRequest(project_id=project_id, username=username)
        self._t.call(
            create_project_member,
            path={"project_id": project_id},
            body=req,
            timeout=timeout,
        )

    @operation("deleteProjectMember")
    def remove_project_member(
        self, project_id: str, username: str, *, timeout: CallTimeout = CLIENT_DEFAULT
    ) -> None:
        """Remove ``username`` from project ``project_id``; idempotent. Scope ``admin:projects:write``."""
        self._t.call(
            delete_project_member,
            path={"project_id": project_id, "username": username},
            timeout=timeout,
        )

    # -- quotas ------------------------------------------------------------------------------

    @operation("getQuotaDefaults")
    def quota_defaults(
        self, *, timeout: CallTimeout = CLIENT_DEFAULT
    ) -> AdminQuotaDefaultsResponse:
        """The per-user quota every user has without an override. Scope ``admin:quotas:read``."""
        out = self._t.call(get_quota_defaults, timeout=timeout)
        return cast(AdminQuotaDefaultsResponse, out)

    @operation("getUserQuotaOverride")
    def get_user_quota(
        self, username: str, *, timeout: CallTimeout = CLIENT_DEFAULT
    ) -> AdminQuotaOverrideResponse:
        """``username``'s quota override. Scope ``admin:quotas:read``."""
        out = self._t.call(
            get_user_quota_override, path={"username": username}, timeout=timeout
        )
        return cast(AdminQuotaOverrideResponse, out)

    @operation("updateUserQuotaOverride")
    def set_user_quota(
        self,
        username: str,
        body: AdminQuotaOverrideRequest | Mapping[str, Any] | None = None,
        *,
        timeout: CallTimeout = CLIENT_DEFAULT,
        **fields: Any,
    ) -> None:
        """Set ``username``'s override (``vcpus_max``, ``ram_mb_max``, ``vm_count_max``,
        ``disk_gb_max``). Scope ``admin:quotas:write``.
        """
        req = build_body(AdminQuotaOverrideRequest, body, fields)
        self._t.call(
            update_user_quota_override,
            path={"username": username},
            body=req,
            timeout=timeout,
        )

    @operation("deleteUserQuotaOverride")
    def delete_user_quota(
        self, username: str, *, timeout: CallTimeout = CLIENT_DEFAULT
    ) -> None:
        """Drop ``username``'s override, back to the defaults. Scope ``admin:quotas:write``."""
        self._t.call(
            delete_user_quota_override, path={"username": username}, timeout=timeout
        )

    @operation("createQuotaBypass")
    def grant_quota_bypass(
        self, username: str, *, timeout: CallTimeout = CLIENT_DEFAULT
    ) -> AdminForceCreateResponse:
        """Let ``username``'s next create exceed their quota, once. Scope ``admin:quotas:write``."""
        out = self._t.call(
            create_quota_bypass, path={"username": username}, timeout=timeout
        )
        return cast(AdminForceCreateResponse, out)

    @operation("getTeamQuotaOverride")
    def get_team_quota(
        self, team_id: str, *, timeout: CallTimeout = CLIENT_DEFAULT
    ) -> AdminTeamQuotaOverrideResponse:
        """Team ``team_id``'s quota override. Scope ``admin:quotas:read``."""
        out = self._t.call(
            get_team_quota_override, path={"team_id": team_id}, timeout=timeout
        )
        return cast(AdminTeamQuotaOverrideResponse, out)

    @operation("updateTeamQuotaOverride")
    def set_team_quota(
        self,
        team_id: str,
        body: AdminTeamQuotaOverrideRequest | Mapping[str, Any] | None = None,
        *,
        timeout: CallTimeout = CLIENT_DEFAULT,
        **fields: Any,
    ) -> None:
        """Set team ``team_id``'s override (the fields of :meth:`set_user_quota`). Scope ``admin:quotas:write``."""
        req = build_body(AdminTeamQuotaOverrideRequest, body, fields)
        self._t.call(
            update_team_quota_override,
            path={"team_id": team_id},
            body=req,
            timeout=timeout,
        )

    @operation("deleteTeamQuotaOverride")
    def delete_team_quota(
        self, team_id: str, *, timeout: CallTimeout = CLIENT_DEFAULT
    ) -> None:
        """Drop team ``team_id``'s override. Scope ``admin:quotas:write``."""
        self._t.call(
            delete_team_quota_override, path={"team_id": team_id}, timeout=timeout
        )

    # -- users -------------------------------------------------------------------------------

    @operation("listAllUsers")
    def list_users(
        self, *, timeout: CallTimeout = CLIENT_DEFAULT
    ) -> builtins.list[AdminUserSummary]:
        """Every user the host knows, with their usage. Scope ``admin:users:read``."""
        out = self._t.call(list_all_users, timeout=timeout)
        return cast(builtins.list[AdminUserSummary], out)

    @operation("getUser")
    def get_user(
        self, username: str, *, timeout: CallTimeout = CLIENT_DEFAULT
    ) -> AdminUserSummary:
        """One user, with their usage. Scope ``admin:users:read``."""
        out = self._t.call(get_user, path={"username": username}, timeout=timeout)
        return cast(AdminUserSummary, out)

    @operation("revokeUserSessions")
    def revoke_user_sessions(
        self, username: str, *, timeout: CallTimeout = CLIENT_DEFAULT
    ) -> RevokeSessionsResponse:
        """End every session ``username`` holds. Scope ``admin:sessions:write``.

        Answers 503 ``unavailable`` when the bastion kept any CLI session: those stay valid,
        everything else was revoked, and calling again retries only the sessions left.
        """
        out = self._t.call(
            revoke_user_sessions, path={"username": username}, timeout=timeout
        )
        return cast(RevokeSessionsResponse, out)

    @operation("offboardUser")
    def offboard_user(
        self,
        username: str,
        *,
        dry_run: bool = False,
        timeout: CallTimeout = CLIENT_DEFAULT,
    ) -> OffboardUserReport:
        """Offboard ``username`` and report each item. Scope ``admin:sessions:write``.

        In one transaction: their CLI sessions, connected apps, bound service keys, every direct
        share to them on any VM, own personal and admin API keys and webhooks. Then, item by
        item: first Cove's own Warpgate role for them is deleted (``warpgate_role``), unbinding
        their VMs' targets (the targets stay; no other role is touched); next their Warpgate
        user is deleted (``warpgate_user``), taking their Warpgate roles, user API tokens,
        passwords, one-time codes and certificates with it (``outcome`` ``not_found`` when
        Warpgate has no such role or user, not a failure); then, belt and braces,
        their SSH keys at Warpgate (``ssh_keys_deleted``), every Warpgate ticket in their
        name (``tickets_deleted``) and every live Warpgate session of theirs
        (``sessions_closed``), pass after pass until one finds nothing new (three at most); then
        the credential sweep runs once more, to end what a still-open session created
        meanwhile; then every team they belong to, every secret in their own scope and every VM
        they own (stopped, never deleted). The report is a 200 even when items failed. A failed
        item is an entry with ``ok`` false and an ``error``, a VM, a ``warpgate_role`` or a
        ``warpgate_user`` with ``outcome`` ``failed``, any
        entry of ``cli_sessions_failed`` (a CLI session Warpgate could not delete; it has no
        ``ok``), or a set ``second_sweep_error`` (the sweep after the sessions closed failed):
        run the call again. ``dry_run=True`` returns the same report and changes nothing; the
        body always carries an explicit ``dry_run`` (the server refuses any other body but an
        empty one). 404 only for a user Cove knows nothing of (never signed in, and no
        membership, share, binding, key, webhook or VM names them).

        Refuses every API key, an admin key included, with 401 ``sudo_required``: it needs a
        ticket or a session.
        """
        out = self._t.call(
            offboard_user,
            path={"username": username},
            body=OffboardUserRequest(dry_run=dry_run),
            timeout=timeout,
        )
        return cast(OffboardUserReport, out)

    @operation("enableUser")
    def enable_user(
        self,
        username: str,
        *,
        timeout: CallTimeout = CLIENT_DEFAULT,
    ) -> EnableUserResponse:
        """Let ``username`` back in after an offboarding shut them out. Scope ``admin:sessions:write``.

        While shut out, every request of theirs is refused with 403 ``user_disabled``, and
        nothing that would hand them a credential or a way in is created, whoever asks. Answers
        the shut-out that was cleared (``disabled_at``, ``disabled_by``, ``reason``); nothing
        offboarding ended comes back. The name is matched regardless of ASCII case. Writes a
        ``user.enabled`` audit row. 404 when the person is not disabled.

        Refuses every API key, an admin key included, with 401 ``sudo_required``: it needs a
        ticket or a session.
        """
        out = self._t.call(
            enable_user,
            path={"username": username},
            timeout=timeout,
        )
        return cast(EnableUserResponse, out)

    # -- every VM and every checkpoint -------------------------------------------------------

    @operation("listAllVms")
    def list_vms(
        self,
        *,
        user: str | None = None,
        limit: int | None = None,
        cursor: str | None = None,
        timeout: CallTimeout = CLIENT_DEFAULT,
    ) -> AdminVmSummaryPage:
        """One page of every user's VMs, or ``user``'s. Scope ``admin:vms:read``."""
        page = self._t.call(
            list_all_vms,
            user=opt(user),
            limit=opt(limit),
            cursor=opt(cursor),
            timeout=timeout,
        )
        return cast(AdminVmSummaryPage, page)

    def iter_vms(
        self,
        *,
        user: str | None = None,
        limit: int | None = None,
        cursor: str | None = None,
        timeout: CallTimeout = CLIENT_DEFAULT,
    ) -> Iterator[AdminVmSummary]:
        """Every VM :meth:`list_vms` lists, following ``next_cursor``."""

        def fetch(c: str | None) -> AdminVmSummaryPage:
            return self.list_vms(user=user, limit=limit, cursor=c, timeout=timeout)

        for vm in paginate(fetch, "vms", cursor=cursor):
            yield vm

    @operation("listAnyCheckpoints")
    def list_checkpoints(
        self,
        *,
        user: str | None = None,
        orphaned: bool | None = None,
        limit: int | None = None,
        cursor: str | None = None,
        timeout: CallTimeout = CLIENT_DEFAULT,
    ) -> AdminCheckpointSummaryPage:
        """One page of every user's checkpoints, or ``user``'s, or only the ``orphaned`` ones.

        Scope ``admin:checkpoints:read``.
        """
        page = self._t.call(
            list_any_checkpoints,
            user=opt(user),
            orphaned=opt(orphaned),
            limit=opt(limit),
            cursor=opt(cursor),
            timeout=timeout,
        )
        return cast(AdminCheckpointSummaryPage, page)

    def iter_checkpoints(
        self,
        *,
        user: str | None = None,
        orphaned: bool | None = None,
        limit: int | None = None,
        cursor: str | None = None,
        timeout: CallTimeout = CLIENT_DEFAULT,
    ) -> Iterator[AdminCheckpointSummary]:
        """Every checkpoint :meth:`list_checkpoints` lists, following ``next_cursor``."""

        def fetch(c: str | None) -> AdminCheckpointSummaryPage:
            return self.list_checkpoints(
                user=user, orphaned=orphaned, limit=limit, cursor=c, timeout=timeout
            )

        for cp in paginate(fetch, "checkpoints", cursor=cursor):
            yield cp

    @operation("deleteAnyCheckpoint")
    def delete_checkpoint(
        self, id: str, *, timeout: CallTimeout = CLIENT_DEFAULT
    ) -> None:
        """Delete any user's checkpoint. Scope ``admin:checkpoints:write``.

        Refuses every API key, an admin key included, with 401 ``sudo_required``: it needs a
        ticket or a session.
        """
        self._t.call(delete_any_checkpoint, path={"id": id}, timeout=timeout)
