# GENERATED by scripts/sync-sdk-python.sh from sdk/python/src/cove_sdk/_async/resources/events.py by unasync — do not edit.
"""``client.events``: the lifecycle and VM event streams (SSE).

Each method returns an :class:`~cove_sdk._async._streams.EventStream` to use in a ``with`` block.
The server closes every event stream after 300 seconds; these reconnect on that clean close by
default (``reconnect=False`` opts out), at most once per second, and stop on cancellation or any
non-2xx. ``vm(name)`` also ends, without reconnecting or raising, after a ``state`` of
``deleted`` or an ``error`` (a failed create). The server does not honour ``Last-Event-ID``, so a
reconnect starts from "now": events between the close and the reconnect are lost. A
:class:`~cove_sdk.streams.StreamLagged` item means the server dropped events for a slow reader;
re-read the state you need.

All three streams are served on every listener, the external bearer one included (scope
``vms:read``).
"""

from __future__ import annotations

from ..._operations import operation
from ...streams import LifecycleEvent, VmEvent
from .._streams import EventStream, decode_lifecycle, decode_vm_event, vm_stream_ended
from .._transport import SyncCoveTransport, TimeoutArg, api_path


class Events:
    """``client.events`` — live event streams."""

    def __init__(self, transport: SyncCoveTransport) -> None:
        self._t = transport

    @operation("streamLifecycleEvents")
    def lifecycle(
        self, *, reconnect: bool = True, timeout: TimeoutArg = None
    ) -> EventStream[LifecycleEvent]:
        """Typed lifecycle events with their actor, for the VMs the caller may see. Scope ``vms:read``.

        Administrators see the fleet; anyone else sees the VMs they owned when the stream
        opened (a reconnect picks up newer ones).
        """
        return EventStream(
            self._t,
            api_path("/api/lifecycle-events"),
            decode=decode_lifecycle,
            reconnect=reconnect,
            timeout=timeout,
        )

    @operation("streamAllVmEvents")
    def all_vms(
        self, *, reconnect: bool = True, timeout: TimeoutArg = None
    ) -> EventStream[VmEvent]:
        """State changes of every VM the caller owns. Scope ``vms:read``.

        ``connected`` (``{"vm_count"}``) comes first, then ``vm-update``, ``vm-created`` and
        ``vm-deleted``."""
        return EventStream(
            self._t,
            api_path("/api/vms/events"),
            decode=decode_vm_event,
            reconnect=reconnect,
            timeout=timeout,
        )

    @operation("streamVmEvents")
    def vm(
        self, name: str, *, reconnect: bool = True, timeout: TimeoutArg = None
    ) -> EventStream[VmEvent]:
        """One VM's events. Scope ``vms:read``.

        ``state`` on connect and on every transition, ``progress`` while it is created, and
        ``error`` if creation fails.

        The stream ends by itself, without reconnecting or raising, right after a ``state`` of
        ``deleted`` or an ``error``: the server ends it there, because the name is free again and
        a later VM under it is a different VM, which needs a new ``vm(name)`` call.
        """
        return EventStream(
            self._t,
            api_path("/api/vms/{name}/events", name=name),
            decode=decode_vm_event,
            reconnect=reconnect,
            timeout=timeout,
            terminal=vm_stream_ended,
        )
