# GENERATED by scripts/sync-sdk-python.sh from sdk/python/src/cove_sdk/_async/resources/keys.py by unasync — do not edit.
"""``client.keys``: API keys (``cvk_`` bearer tokens) — the caller's own, a team's, and service keys."""

from __future__ import annotations

import builtins
from collections.abc import Mapping
from typing import Any, cast

from ..._args import build_body, opt
from ..._generated.api.api_keys import (
    create_api_key,
    list_api_keys,
    revoke_api_key,
    revoke_api_key_by_token,
    rotate_api_key,
)
from ..._generated.models import (
    CreatedKey,
    CreateKeyRequest,
    KeySummary,
    RevokeKeyByTokenRequest,
)
from ..._operations import operation
from ...errors import CoveError, _parse_api_version
from .._transport import CLIENT_DEFAULT, SyncCoveTransport, CallTimeout, api_path

SERVICE_KEYS_MIN_API_VERSION: int = 6
"""First server API version that serves service keys: ``service`` and ``member`` on create, and
``service=True`` on list. An older server ignores them, so it would mint a team key, or a personal
key acting as the caller, and list the caller's own keys. Equal to the server's
``SERVICE_KEYS_API_VERSION``; ``cove/cove-cli/tests/version_drift.rs`` checks the two stay equal."""


class Keys:
    """``client.keys`` — list, create, revoke and rotate API keys."""

    def __init__(self, transport: SyncCoveTransport) -> None:
        self._t = transport

    @operation("listApiKeys")
    def list(
        self,
        *,
        team: str | None = None,
        service: bool | None = None,
        timeout: CallTimeout = CLIENT_DEFAULT,
    ) -> builtins.list[KeySummary]:
        """List API keys (never their tokens). Scope ``keys:manage``.

        The caller's own keys by default; ``team="<name>"`` lists that team's and
        ``service=True`` the service keys (both administrators only). A summary's
        ``subject_type``, ``bound_team`` and ``bound_member`` say whose key it is.

        ``service=True`` first reads the server's API version (a ``GET /api/whoami``) and raises
        :class:`~cove_sdk.CoveError`, sending nothing more, unless it is
        :data:`SERVICE_KEYS_MIN_API_VERSION` or later: an older server would list the caller's
        own keys instead.
        """
        if service:
            self._require_service_keys(timeout)
        keys = self._t.call(
            list_api_keys, team=opt(team), service=opt(service), timeout=timeout
        )
        return cast(builtins.list[KeySummary], keys)

    @operation("createApiKey")
    def create(
        self,
        body: CreateKeyRequest | Mapping[str, Any] | None = None,
        *,
        timeout: CallTimeout = CLIENT_DEFAULT,
        **fields: Any,
    ) -> CreatedKey:
        """Create an API key. Scope ``keys:manage``.

        Fields are ``CreateKeyRequest``'s, under their wire names, as keywords or as ``body``:
        ``label``, ``scopes`` (omit for the server's default set; an empty list is refused with
        422), ``expires_in_secs``, ``admin_key``, ``team``, ``service`` and ``member``. An option
        not given is not sent. Four kinds of key, picked by the fields:

        - **Personal key** (no ``team``, ``service`` or ``admin_key``): acts as you. It never
          expires unless ``expires_in_secs`` is set, within the server's
          ``[auth] max_key_lifetime_days`` cap, and it cannot hold ``admin`` or ``admin:*``.
        - **Admin key** (``admin_key=True``): the only kind that may hold ``admin`` or
          ``admin:*``, and it must hold at least one. It needs ``expires_in_secs`` within
          ``[auth] admin_max_key_lifetime_days`` (default 30, never above the general cap). Only
          an administrator (``[auth] admins``) mints one, and only from a signed-in session (a
          ticket, SSH or the web UI): any API key, an admin key included, gets 403. Never with
          ``team`` or ``service``.
        - **Team key** (``team="<name>"``): administrators only (403 otherwise). It needs
          ``expires_in_secs`` within the general cap and cannot hold ``keys:manage``,
          ``access:write``, ``admin`` or ``admin:*``.
        - **Service key** (``service="<name>"``, minted as ``svc:<name>``): administrators only
          (403 otherwise). Exactly one of ``team`` or ``member`` names its binding: the team, or
          the one member, its VMs are charged to and controlled by; ``member`` without
          ``service`` is refused. It needs ``expires_in_secs`` within the general cap and cannot
          hold ``keys:manage``, ``access:write``, ``admin`` or ``admin:*``.

        A team or service key cannot mint keys itself. The token is in ``raw_token`` and is shown
        this once. The returned model's repr prints that token, so do not log the return value.

        With ``service`` or ``member`` set, it first reads the server's API version (a
        ``GET /api/whoami``) and raises :class:`~cove_sdk.CoveError`, sending nothing more, unless
        it is :data:`SERVICE_KEYS_MIN_API_VERSION` or later; a missing, zero or unreadable version,
        or a probe that fails, is refused too. An older server ignores both fields and would mint a
        personal key acting as the caller, or a team key, and the reply would not say so.
        """
        req = build_body(CreateKeyRequest, body, fields)
        # A field given is a str; an absent or null one (UNSET, None) asks nothing of the server.
        if isinstance(req.service, str) or isinstance(req.member, str):
            self._require_service_keys(timeout)
        key = self._t.call(create_api_key, body=req, timeout=timeout)
        return cast(CreatedKey, key)

    def _require_service_keys(self, timeout: CallTimeout) -> None:
        """Refuse a service-key call unless the server says it speaks
        :data:`SERVICE_KEYS_MIN_API_VERSION` or later; nothing shows an older one is new enough."""
        # /api/whoami is in the contract and served on every listener, and every successful reply
        # carries x-cove-api-version. Read it from this reply, not the transport's last-seen
        # version, which a reply without the header would leave at an earlier response's value.
        try:
            response = self._t.request("GET", api_path("/api/whoami"), timeout=timeout)
        except CoveError as exc:
            raise CoveError(
                f"could not read the server's API version ({exc}), so cannot confirm it serves "
                f"service keys (API version {SERVICE_KEYS_MIN_API_VERSION} or later); "
                "nothing was sent"
            ) from exc
        version = _parse_api_version(response.headers.get("x-cove-api-version"))
        if not version or version < SERVICE_KEYS_MIN_API_VERSION:
            raise CoveError(
                f"this server speaks API version {'unknown' if version is None else version}; service keys need API "
                f"version {SERVICE_KEYS_MIN_API_VERSION} or later, and an older server would mint "
                "or list the wrong kind of key; nothing was sent"
            )

    @operation("revokeApiKey")
    def revoke(self, id: str, *, timeout: CallTimeout = CLIENT_DEFAULT) -> None:
        """Revoke key ``id``. Scope ``keys:manage``.

        Your own key, or anyone's as an administrator (signed in or through an admin key).
        Requests with the key are refused 401 at once; streams already open with it (events,
        console, exec) end within the server's 15 s re-check interval.
        """
        self._t.call(revoke_api_key, path={"id": id}, timeout=timeout)

    @operation("revokeApiKeyByToken")
    def revoke_by_token(
        self, token: str, *, timeout: CallTimeout = CLIENT_DEFAULT
    ) -> None:
        """Revoke an API key by presenting it: holding the key is the proof.

        Any key works, yours or one you found, and the call needs no scope (on the bearer
        listener, no credential at all). Returns alike whether the key was live (it is revoked,
        as by its owner), already revoked, unknown or not a key, so it tells you nothing about
        it. Never log ``token``.
        """
        self._t.call(
            revoke_api_key_by_token,
            body=RevokeKeyByTokenRequest(token=token),
            timeout=timeout,
        )

    @operation("rotateApiKey")
    def rotate(self, id: str, *, timeout: CallTimeout = CLIENT_DEFAULT) -> CreatedKey:
        """Replace key ``id``'s token; the new one is in ``raw_token``, shown this once. Scope ``keys:manage``.

        The returned model's repr prints that token, so do not log the return value.
        """
        key = self._t.call(rotate_api_key, path={"id": id}, timeout=timeout)
        return cast(CreatedKey, key)
