# GENERATED by scripts/sync-sdk-python.sh from sdk/python/src/cove_sdk/_async/resources/vms.py by unasync — do not edit.
"""``client.vms``: VM lifecycle, ports and invites, monitoring, streamed and buffered exec.

``exec`` streams a command's output (``exec_collect`` gathers it) and ``stream_console`` tails the
serial console, both over SSE (``_streams``); ``exec_with_secrets`` posts to the dedicated
``/exec-with-secrets`` route (the selector-on-``/exec`` form is refused from API version 5, so
this SDK never sends it).
"""

from __future__ import annotations

import builtins
from collections.abc import Iterator, Iterable, Mapping, Sequence
from typing import Any, cast

from ..._args import build_body, opt
from ..._colour import sync_sleep, monotonic
from ..._generated.api.monitoring import (
    exec_vm_with_secrets,
    get_vm_console,
    get_vm_stats,
    get_vm_telemetry,
    list_vm_events,
    list_vm_processes,
)
from ..._generated.api.proxy import (
    create_vm_port,
    create_vm_port_invite,
    delete_vm_port,
    get_vm_url,
    list_vm_invites,
    list_vm_ports,
    revoke_vm_invite,
    set_vm_port_public,
)
from ..._generated.api.vms import (
    clone_vm,
    connect_vm,
    create_vm,
    delete_vm,
    get_vm,
    grant_vm_access,
    list_shared_vms,
    list_vm_access,
    list_vms,
    pause_vm,
    resize_vm,
    resume_vm,
    revoke_vm_access,
    start_vm,
    stop_vm,
    wake_vm,
)
from ..._generated.models import (
    AddPortRequest,
    CloneRequest,
    CloneResponse,
    ConnectionInfo,
    CreateInviteRequest,
    CreateVmRequest,
    CreateVmResponse,
    ExecOutputDto,
    ExecWithSecretsRequest,
    GrantShareOutcome,
    GrantShareRequest,
    ProxyInvite,
    ProxyPortInfo,
    ProxyUrlInfo,
    RemovalResponse,
    ResizeRequest,
    ResizeResult,
    RevokeShareOutcome,
    SetPublicRequest,
    SharedVmSummary,
    ShareEntry,
    VmConsole,
    VmDetail,
    VmEvent,
    VmEventsPage,
    VmProcess,
    VmStats,
    VmSummary,
    VmSummaryPage,
    VmTelemetrySeries,
    WakeRequest,
)
from ..._operations import operation
from ...errors import CoveDecodeError, CoveError, CoveTimeoutError
from ...streams import (
    ExecError,
    ExecExit,
    ExecPaused,
    ExecResult,
    ExecStderr,
    ExecStdout,
)
from .._pagination import paginate
from .files import Files
from .._streams import EventStream, ExecStream, decode_console
from .._transport import (
    CLIENT_DEFAULT,
    SyncCoveTransport,
    CallTimeout,
    TimeoutArg,
    api_path,
)


class Vms:
    """``client.vms`` — VM lifecycle, ports, monitoring. Scopes are named per method."""

    files: Files
    """Single-file transfer in and out of a running VM: ``stat``, ``download``, ``upload``."""

    def __init__(self, transport: SyncCoveTransport) -> None:
        self._t = transport
        self.files = Files(transport)

    # -- listing and lifecycle -------------------------------------------------------------------

    @operation("listVms")
    def list(
        self,
        *,
        state: str | None = None,
        tag: str | Sequence[str] | None = None,
        limit: int | None = None,
        cursor: str | None = None,
        timeout: CallTimeout = CLIENT_DEFAULT,
    ) -> VmSummaryPage:
        """One page of the VMs visible to the caller, ordered by name. Scope ``vms:read``.

        One page is not every VM: use :meth:`iter` for "all my VMs". ``state`` is a
        ``VmState`` value (``"running"``, ``"stopped"``, ...). ``tag`` is ``key=value`` with a
        non-empty key, or a list of them: only VMs carrying every one are listed. ``limit`` is at
        least 1. A filter value the server cannot apply is refused
        with a 400 ``validation_failed`` naming the parameter, never ignored; so is a query key
        other than ``state``, ``tag``, ``limit`` and ``cursor``.
        """
        tags = (
            [tag]
            if isinstance(tag, str)
            else None
            if tag is None
            else builtins.list(tag)
        )
        page = self._t.call(
            list_vms,
            state=opt(state),
            tag=opt(tags),
            limit=opt(limit),
            cursor=opt(cursor),
            timeout=timeout,
        )
        return cast(VmSummaryPage, page)

    def iter(
        self,
        *,
        state: str | None = None,
        tag: str | Sequence[str] | None = None,
        limit: int | None = None,
        cursor: str | None = None,
        timeout: CallTimeout = CLIENT_DEFAULT,
    ) -> Iterator[VmSummary]:
        """Every VM visible to the caller, following ``next_cursor``. Scope ``vms:read``.

        ``limit`` is the page size; ``timeout`` applies to each page.
        """

        def fetch(c: str | None) -> VmSummaryPage:
            return self.list(
                state=state, tag=tag, limit=limit, cursor=c, timeout=timeout
            )

        for vm in paginate(fetch, "vms", cursor=cursor):
            yield vm

    @operation("createVm")
    def create(
        self,
        body: CreateVmRequest | Mapping[str, Any] | None = None,
        *,
        timeout: CallTimeout = CLIENT_DEFAULT,
        **fields: Any,
    ) -> CreateVmResponse:
        """Create a VM. Scope ``vms:write``.

        Fields are ``CreateVmRequest``'s (``name``, ``image``, ``cpus``, ``memory_mb``,
        ``initial_tags`` as a ``{key: value}`` map, ...), as keywords or as ``body``. The server
        answers 202 and creates in the background: follow with :meth:`wait_for_state`.
        """
        req = build_body(CreateVmRequest, body, fields)
        return cast(
            CreateVmResponse, self._t.call(create_vm, body=req, timeout=timeout)
        )

    @operation("getVm")
    def get(self, name: str, *, timeout: CallTimeout = CLIENT_DEFAULT) -> VmDetail:
        """One VM. Scope ``vms:read``. A VM that exists but is not yours is a 404, like a missing one."""
        vm = self._t.call(get_vm, path={"name": name}, timeout=timeout)
        return cast(VmDetail, vm)

    @operation("deleteVm")
    def delete(self, name: str, *, timeout: CallTimeout = CLIENT_DEFAULT) -> None:
        """Delete a VM (202: continues in the background). Scope ``vms:write``."""
        self._t.call(delete_vm, path={"name": name}, timeout=timeout)

    @operation("stopVm")
    def stop(self, name: str, *, timeout: CallTimeout = CLIENT_DEFAULT) -> None:
        """Stop a VM (graceful, asynchronous). Scope ``vms:write``. 409 from an invalid state."""
        self._t.call(stop_vm, path={"name": name}, timeout=timeout)

    @operation("startVm")
    def start(self, name: str, *, timeout: CallTimeout = CLIENT_DEFAULT) -> None:
        """Start a stopped VM. Scope ``vms:write``. 409 from an invalid state or admission."""
        self._t.call(start_vm, path={"name": name}, timeout=timeout)

    @operation("pauseVm")
    def pause(self, name: str, *, timeout: CallTimeout = CLIENT_DEFAULT) -> None:
        """Pause a running VM. Scope ``vms:write``."""
        self._t.call(pause_vm, path={"name": name}, timeout=timeout)

    @operation("resumeVm")
    def resume(self, name: str, *, timeout: CallTimeout = CLIENT_DEFAULT) -> None:
        """Resume a paused VM. Scope ``vms:write``."""
        self._t.call(resume_vm, path={"name": name}, timeout=timeout)

    @operation("wakeVm")
    def wake(
        self,
        name: str,
        body: WakeRequest | Mapping[str, Any] | None = None,
        *,
        timeout: CallTimeout = CLIENT_DEFAULT,
        **fields: Any,
    ) -> None:
        """Wake a VM from ``checkpoint_id`` or the latest checkpoint. Scope ``vms:write``.

        A hibernated VM wakes from a checkpoint with memory; a stopped VM wakes from a disk-only
        one, whose disk replaces the VM's. Without ``checkpoint_id``, a stopped VM whose latest
        checkpoint is disk-only is refused with 409 ``disk_rollback_not_named`` and nothing
        changes: call ``start`` to boot the current disk, or pass the checkpoint's id to roll back.
        """
        req = build_body(WakeRequest, body, fields)
        self._t.call(wake_vm, path={"name": name}, body=req, timeout=timeout)

    @operation("resizeVm")
    def resize(
        self,
        name: str,
        body: ResizeRequest | Mapping[str, Any] | None = None,
        *,
        timeout: CallTimeout = CLIENT_DEFAULT,
        **fields: Any,
    ) -> ResizeResult:
        """Resize ``cpus``/``memory_mb`` (running) or grow ``disk_size_gb`` (stopped). Scope ``vms:write``."""
        req = build_body(ResizeRequest, body, fields)
        result = self._t.call(resize_vm, path={"name": name}, body=req, timeout=timeout)
        return cast(ResizeResult, result)

    @operation("cloneVm")
    def clone(
        self,
        source: str,
        body: CloneRequest | Mapping[str, Any] | None = None,
        *,
        timeout: CallTimeout = CLIENT_DEFAULT,
        **fields: Any,
    ) -> CloneResponse:
        """Clone ``source`` as ``new_vm_name`` (optionally from ``source_checkpoint_id``). Scope ``vms:write``."""
        req = build_body(CloneRequest, body, fields)
        result = self._t.call(
            clone_vm, path={"source": source}, body=req, timeout=timeout
        )
        return cast(CloneResponse, result)

    @operation("connectVm")
    def connect(
        self, name: str, *, timeout: CallTimeout = CLIENT_DEFAULT
    ) -> ConnectionInfo:
        """Mint an SSH connection ticket. Scope ``vms:write``."""
        info = self._t.call(connect_vm, path={"name": name}, timeout=timeout)
        return cast(ConnectionInfo, info)

    def wait_for_state(
        self,
        name: str,
        states: str | Iterable[str],
        *,
        timeout: float,
        interval: float = 1.0,
    ) -> VmDetail:
        """Poll :meth:`get` until the VM's state is one of ``states``; return that ``VmDetail``.

        ``timeout`` is the whole wait, in seconds, and bounds each poll too; when it passes,
        :class:`~cove_sdk.CoveTimeoutError` names the last state seen. Errors from ``get`` (a 404
        after a failed create, say) propagate at once. A VM that settles in a state not in
        ``states`` -- ``failed`` or ``deleted``, say -- is not an error here: polling goes on
        until the deadline, and the ``CoveTimeoutError`` then names that last state.
        """
        wanted = {states} if isinstance(states, str) else set(states)
        deadline = monotonic() + timeout
        last = "none: no poll finished"
        while True:
            remaining = deadline - monotonic()
            if remaining <= 0:
                raise CoveTimeoutError(
                    f"VM {name!r} did not reach {sorted(wanted)} within {timeout}s;"
                    f" last state {last}"
                )
            vm = self.get(name, timeout=remaining)
            if str(vm.state) in wanted:
                return vm
            last = repr(str(vm.state))
            sync_sleep(max(0.0, min(interval, deadline - monotonic())))

    # -- proxy: URLs, ports, invites -------------------------------------------------------------

    @operation("getVmUrl")
    def get_url(
        self, name: str, *, timeout: CallTimeout = CLIENT_DEFAULT
    ) -> ProxyUrlInfo:
        """The VM's SSH URL and per-port HTTPS URLs. Scope ``vms:read``."""
        info = self._t.call(get_vm_url, path={"name": name}, timeout=timeout)
        return cast(ProxyUrlInfo, info)

    @operation("createVmPort")
    def add_port(
        self, name: str, port: int, *, timeout: CallTimeout = CLIENT_DEFAULT
    ) -> ProxyPortInfo | None:
        """Expose guest ``port`` through the HTTPS proxy. Scope ``ports:write``.

        Idempotent: a port that is already published (a retry, or the primary port) is
        returned as it stands, unchanged. Returns the port and its URL; ``None`` from a
        server older than API version 7, which answers without a body.
        """
        req = build_body(AddPortRequest, None, {"port": port})
        try:
            info = self._t.call(
                create_vm_port, path={"name": name}, body=req, timeout=timeout
            )
        except CoveDecodeError as exc:
            # A server older than API version 7 answers a publish with an empty 201 or 200.
            if not exc.body.strip():
                return None
            raise
        return cast(ProxyPortInfo | None, info)

    @operation("deleteVmPort")
    def remove_port(
        self, name: str, port: int, *, timeout: CallTimeout = CLIENT_DEFAULT
    ) -> RemovalResponse | None:
        """Stop exposing ``port``. Scope ``ports:write``.

        Idempotent: ``existed`` is ``False`` when the port was not published. ``None``
        from a server older than API version 7, which does not say.
        """
        out = self._t.call(
            delete_vm_port, path={"name": name, "port": port}, timeout=timeout
        )
        return cast(RemovalResponse | None, out)

    @operation("setVmPortPublic")
    def set_port_public(
        self,
        name: str,
        port: int,
        public: bool,
        *,
        timeout: CallTimeout = CLIENT_DEFAULT,
    ) -> None:
        """Turn unauthenticated access to ``port`` on or off. Scope ``ports:write``."""
        req = build_body(SetPublicRequest, None, {"public": public})
        self._t.call(
            set_vm_port_public,
            path={"name": name, "port": port},
            body=req,
            timeout=timeout,
        )

    @operation("listVmPorts")
    def list_ports(
        self, name: str, *, timeout: CallTimeout = CLIENT_DEFAULT
    ) -> builtins.list[ProxyPortInfo]:
        """Every registered port and its exposure. Scope ``ports:read``."""
        ports = self._t.call(list_vm_ports, path={"name": name}, timeout=timeout)
        return cast(builtins.list[ProxyPortInfo], ports)

    @operation("createVmPortInvite")
    def create_invite(
        self,
        name: str,
        port: int,
        *,
        ttl_secs: int,
        timeout: CallTimeout = CLIENT_DEFAULT,
    ) -> ProxyInvite:
        """A share link to ``port`` valid for ``ttl_secs``. Scope ``ports:write``."""
        req = build_body(CreateInviteRequest, None, {"ttl_secs": ttl_secs})
        invite = self._t.call(
            create_vm_port_invite,
            path={"name": name, "port": port},
            body=req,
            timeout=timeout,
        )
        return cast(ProxyInvite, invite)

    @operation("listVmInvites")
    def list_invites(
        self, name: str, *, timeout: CallTimeout = CLIENT_DEFAULT
    ) -> builtins.list[ProxyInvite]:
        """The VM's active invite links. Scope ``ports:read``."""
        invites = self._t.call(list_vm_invites, path={"name": name}, timeout=timeout)
        return cast(builtins.list[ProxyInvite], invites)

    @operation("revokeVmInvite")
    def revoke_invite(
        self, name: str, invite_id: str, *, timeout: CallTimeout = CLIENT_DEFAULT
    ) -> None:
        """Revoke an invite link. Scope ``ports:write``."""
        self._t.call(
            revoke_vm_invite,
            path={"name": name, "invite_id": invite_id},
            timeout=timeout,
        )

    # -- monitoring ------------------------------------------------------------------------------

    @operation("listVmProcesses")
    def processes(
        self,
        name: str,
        *,
        top: int | None = None,
        timeout: CallTimeout = CLIENT_DEFAULT,
    ) -> builtins.list[VmProcess]:
        """The guest's top processes. Scope ``vms:exec`` (process names are guest content)."""
        procs = self._t.call(
            list_vm_processes, path={"name": name}, top=opt(top), timeout=timeout
        )
        return cast(builtins.list[VmProcess], procs)

    @operation("getVmStats")
    def stats(self, name: str, *, timeout: CallTimeout = CLIENT_DEFAULT) -> VmStats:
        """Point-in-time guest stats. Scope ``vms:read``."""
        stats = self._t.call(get_vm_stats, path={"name": name}, timeout=timeout)
        return cast(VmStats, stats)

    @operation("getVmConsole")
    def console(
        self,
        name: str,
        *,
        lines: int | None = None,
        timeout: CallTimeout = CLIENT_DEFAULT,
    ) -> VmConsole:
        """The tail of the serial console. Scope ``vms:exec`` (console output is guest content)."""
        console = self._t.call(
            get_vm_console, path={"name": name}, lines=opt(lines), timeout=timeout
        )
        return cast(VmConsole, console)

    @operation("getVmTelemetry")
    def telemetry(
        self,
        name: str,
        *,
        from_: int | None = None,
        to: int | None = None,
        step: int | None = None,
        limit: int | None = None,
        timeout: CallTimeout = CLIENT_DEFAULT,
    ) -> VmTelemetrySeries:
        """The VM's telemetry series (``from_`` is sent as ``from``). Scope ``vms:read``."""
        series = self._t.call(
            get_vm_telemetry,
            path={"name": name},
            from_=opt(from_),
            to=opt(to),
            step=opt(step),
            limit=opt(limit),
            timeout=timeout,
        )
        return cast(VmTelemetrySeries, series)

    @operation("listVmEvents")
    def events_log(
        self,
        name: str,
        *,
        cursor: str | None = None,
        limit: int | None = None,
        timeout: CallTimeout = CLIENT_DEFAULT,
    ) -> VmEventsPage:
        """One page of the VM's event log. Scope ``vms:read``."""
        page = self._t.call(
            list_vm_events,
            path={"name": name},
            cursor=opt(cursor),
            limit=opt(limit),
            timeout=timeout,
        )
        return cast(VmEventsPage, page)

    def iter_events_log(
        self,
        name: str,
        *,
        limit: int | None = None,
        cursor: str | None = None,
        timeout: CallTimeout = CLIENT_DEFAULT,
    ) -> Iterator[VmEvent]:
        """Every entry of the VM's event log, following ``next_cursor``. Scope ``vms:read``."""

        def fetch(c: str | None) -> VmEventsPage:
            return self.events_log(name, cursor=c, limit=limit, timeout=timeout)

        for event in paginate(fetch, "events", cursor=cursor):
            yield event

    @operation("execVmWithSecrets")
    def exec_with_secrets(
        self,
        name: str,
        *,
        command: Sequence[str],
        selector: Any,
        timeout_secs: int | None = None,
        timeout: CallTimeout = CLIENT_DEFAULT,
    ) -> ExecOutputDto:
        """Run ``command`` with the ``selector``'s secrets injected; buffered. Scope ``vms:exec``.

        ``selector`` is an ``InjectSelector`` model or its JSON shape. Every secret on the VM:
        ``{"kind": "all"}``. A named subset: ``{"kind": "subset", "names": ["API_KEY"]}``.
        The setup-only secrets stored under a tag: ``{"kind": "setup_tag", "tag": "bootstrap"}``.
        ``timeout_secs`` is the deadline the server puts on the guest command, 30 s when omitted and
        at most 3600 (the server refuses a larger value with 400 ``validation_failed``).
        Past it the guest SIGKILLs the command's whole process group and the result has
        ``exit_code`` 124 and ``timed_out`` true, with the output written before then; a
        ``setup_tag`` selector's secrets are still wiped. A command that exits 124 on its own has
        ``timed_out`` false. ``timeout`` is this client's bound on the whole buffered request, so
        keep it longer than ``timeout_secs``. 503 ``feature_disabled`` when secrets are off.
        """
        fields: dict[str, Any] = {"command": list(command), "selector": selector}
        if timeout_secs is not None:
            fields["timeout_secs"] = timeout_secs
        req = build_body(ExecWithSecretsRequest, None, fields)
        out = self._t.call(
            exec_vm_with_secrets, path={"name": name}, body=req, timeout=timeout
        )
        return cast(ExecOutputDto, out)

    # -- streams ---------------------------------------------------------------------------------

    @operation("execVm")
    def exec(
        self,
        name: str,
        *,
        command: Sequence[str],
        timeout_secs: int | None = None,
        cwd: str | None = None,
        env: Mapping[str, str] | None = None,
        user: str | None = None,
        login: bool | None = None,
        timeout: TimeoutArg = None,
    ) -> ExecStream:
        """Run ``command`` in the guest, streaming its output. Scope ``vms:exec``.

        Use the result in a ``with`` block and iterate it: ``ExecStdout``/``ExecStderr`` chunks
        (concatenate verbatim), then exactly one of ``ExecExit``/``ExecError``/``ExecPaused``.
        Nothing is sent until the block is entered. ``timeout_secs`` is the deadline the server
        enforces on the command (30 s when omitted): the guest then SIGKILLs the command and
        everything that stayed in its process group, and the stream ends with ``ExecExit`` code
        124 and ``timed_out`` true. ``timeout`` is this client's: by default only the connect
        phase is bounded, and a number bounds the idle time between chunks.

        The command runs as root in a login-like environment (``HOME=/root``, starting in
        ``/root``). ``cwd`` sets the working directory (relative to the account's home),
        ``env`` adds variables that win over the defaults (at most 128), ``user`` runs it as
        another account in the VM's ``/etc/passwd``, and ``login`` runs it through that
        account's login shell so its profile files apply. A VM whose guest agent predates
        protocol 9 refuses an exec that sets any of them (``ExecError``); one that sets none
        is sent exactly as before.
        """
        body: dict[str, object] = {"command": builtins.list(command)}
        if timeout_secs is not None:
            body["timeout_secs"] = timeout_secs
        if cwd is not None:
            body["cwd"] = cwd
        if env is not None:
            body["env"] = dict(env)
        if user is not None:
            body["user"] = user
        if login:
            body["login"] = True  # False is the default: leave it out of a plain exec
        return ExecStream(
            self._t,
            api_path("/api/vms/{name}/exec", name=name),
            body=body,
            timeout=timeout,
        )

    def exec_collect(
        self,
        name: str,
        *,
        command: Sequence[str],
        timeout_secs: int | None = None,
        cwd: str | None = None,
        env: Mapping[str, str] | None = None,
        user: str | None = None,
        login: bool | None = None,
        timeout: TimeoutArg = None,
    ) -> ExecResult:
        """Run ``command`` through :meth:`exec` and gather its output. Scope ``vms:exec``.

        Raises :class:`~cove_sdk.errors.CoveError` when the exec ends in ``error`` or ``paused``,
        or when the stream ends without a terminal event. A command killed at its
        ``timeout_secs`` deadline returns ``exit_code`` 124 with ``timed_out`` true (it used to
        raise ``exec failed: command timed out after Ns``).
        """
        stdout: builtins.list[str] = []
        stderr: builtins.list[str] = []
        with self.exec(
            name,
            command=command,
            timeout_secs=timeout_secs,
            cwd=cwd,
            env=env,
            user=user,
            login=login,
            timeout=timeout,
        ) as stream:
            for event in stream:
                if isinstance(event, ExecStdout):
                    stdout.append(event.data)
                elif isinstance(event, ExecStderr):
                    stderr.append(event.data)
                elif isinstance(event, ExecExit):
                    return ExecResult(
                        "".join(stdout), "".join(stderr), event.code, event.timed_out
                    )
                elif isinstance(event, ExecError):
                    raise CoveError(f"exec failed: {event.error}")
                elif isinstance(event, ExecPaused):
                    raise CoveError(
                        "exec interrupted: VM left Running mid-exec "
                        f"({event.reason}, new state: {event.new_state})"
                    )
        raise CoveError("exec stream ended without a terminal event")

    @operation("streamVmConsole")
    def stream_console(
        self,
        name: str,
        *,
        lines: int | None = None,
        reconnect: bool = False,
        timeout: TimeoutArg = None,
    ) -> EventStream[str]:
        """Tail the VM's serial console, one raw line per item. Scope ``vms:exec``.

        ``lines`` historical lines come first (the server's default is 20), then the live tail,
        which never ends on its own: leave the ``with`` block to stop. No reconnect by default --
        a console tail is not an event log, and a reconnect replays the backlog.
        """
        return EventStream(
            self._t,
            api_path("/api/vms/{name}/console/stream", name=name),
            decode=decode_console,
            params={"lines": lines},
            reconnect=reconnect,
            timeout=timeout,
        )

    # -- sharing -----------------------------------------------------------------------------

    @operation("listSharedVms")
    def shared_with_me(
        self, *, timeout: CallTimeout = CLIENT_DEFAULT
    ) -> builtins.list[SharedVmSummary]:
        """VMs other people shared with the caller, each with its ``owner``. Scope ``vms:read``."""
        out = self._t.call(list_shared_vms, timeout=timeout)
        return cast(builtins.list[SharedVmSummary], out)

    @operation("listVmAccess")
    def access(
        self, name: str, *, timeout: CallTimeout = CLIENT_DEFAULT
    ) -> builtins.list[ShareEntry]:
        """Who VM ``name`` is shared with. Its owner and administrators only; anyone else gets the
        404 a missing VM gets. Scope ``access:read``.
        """
        out = self._t.call(list_vm_access, path={"name": name}, timeout=timeout)
        return cast(builtins.list[ShareEntry], out)

    @operation("grantVmAccess")
    def share(
        self,
        name: str,
        *,
        subject_type: str,
        subject_id: str,
        role: str,
        timeout: CallTimeout = CLIENT_DEFAULT,
    ) -> GrantShareOutcome:
        """Share VM ``name`` with a user or a team.

        ``subject_type`` is ``"user"`` or ``"team"``, ``subject_id`` the username or team name,
        ``role`` ``"user"`` or ``"collaborator"``. ``user_known`` is ``False`` when the user has
        not signed in yet; the share still applies from their first login. Its owner and
        administrators only; anyone else gets a 404. Scope ``access:write``.
        """
        req = GrantShareRequest(
            subject_type=subject_type, subject_id=subject_id, role=role
        )
        out = self._t.call(
            grant_vm_access, path={"name": name}, body=req, timeout=timeout
        )
        return cast(GrantShareOutcome, out)

    @operation("revokeVmAccess")
    def unshare(
        self,
        name: str,
        subject_type: str,
        subject_id: str,
        *,
        timeout: CallTimeout = CLIENT_DEFAULT,
    ) -> RevokeShareOutcome:
        """Stop sharing VM ``name`` with a user or team (``subject_type`` ``"user"`` or
        ``"team"``). ``unconfirmed_edges`` and ``unconfirmed_sessions`` list what the server could
        not yet confirm closed; it keeps retrying them. Scope ``access:write``.
        """
        out = self._t.call(
            revoke_vm_access,
            path={"name": name, "subject_type": subject_type, "subject_id": subject_id},
            timeout=timeout,
        )
        return cast(RevokeShareOutcome, out)
