from enum import StrEnum


class ErrorCode(StrEnum):
    ADMIN_REQUIRED = "admin_required"
    CAPACITY_EXHAUSTED = "capacity_exhausted"
    CHECKPOINT_CONFLICT = "checkpoint_conflict"
    CLI_DISTRIBUTION_NOT_CONFIGURED = "cli_distribution_not_configured"
    CLI_TOO_OLD = "CLI_TOO_OLD"
    CLONE_SOURCE_NOT_FOUND = "clone_source_not_found"
    CREDENTIAL_EXPIRED = "credential_expired"
    CREDENTIAL_INVALID = "credential_invalid"
    CREDENTIAL_MISSING = "credential_missing"
    CRYPTO_ERROR = "crypto_error"
    DATABASE_UNAVAILABLE = "database_unavailable"
    FEATURE_DISABLED = "feature_disabled"
    FILE_NOT_FOUND = "file_not_found"
    FILE_NOT_REGULAR = "file_not_regular"
    FILE_PATH_DENIED = "file_path_denied"
    FILE_TOO_LARGE = "file_too_large"
    GUEST_AGENT_TOO_OLD = "guest_agent_too_old"
    GUEST_DISK_FULL = "guest_disk_full"
    IDENTITY_INVALID = "identity_invalid"
    IDENTITY_MISSING = "identity_missing"
    IMAGE_REJECTED = "image_rejected"
    INTERNAL_ERROR = "internal_error"
    INVALID_CONFIG = "invalid_config"
    INVALID_STATE_TRANSITION = "invalid_state_transition"
    INVALID_VM_NAME = "invalid_vm_name"
    PLATFORM_NOT_AVAILABLE = "platform_not_available"
    PORT_NOT_ALLOWED = "port_not_allowed"
    PORT_NOT_PRIMARY = "port_not_primary"
    PRIMARY_PORT_NOT_REMOVABLE = "primary_port_not_removable"
    RATE_LIMITED = "rate_limited"
    RESOURCE_NOT_FOUND = "resource_not_found"
    SCOPE_DENIED = "scope_denied"
    SECRET_NAME_INVALID = "secret_name_invalid"
    STORAGE_ERROR = "storage_error"
    SUDO_REQUIRED = "sudo_required"
    TAG_INVALID = "tag_invalid"
    TAG_INVALID_KEY = "tag_invalid_key"
    TAG_INVALID_VALUE = "tag_invalid_value"
    TAG_RESERVED_PREFIX = "tag_reserved_prefix"
    TEAM_HAS_VMS = "team_has_vms"
    TEAM_NOT_FOUND = "team_not_found"
    TICKET_REQUIRED = "ticket_required"
    TOO_MANY_TAGS = "too_many_tags"
    UNAVAILABLE = "unavailable"
    UNKNOWN_IMAGE = "unknown_image"
    USER_NOT_PROVISIONED = "user_not_provisioned"
    VALIDATION_FAILED = "validation_failed"
    VM_ACCESS_DENIED = "vm_access_denied"
    VM_NAME_TAKEN = "vm_name_taken"
    VM_NOT_FOUND = "vm_not_found"
    WAKE_TARGET_NOT_FOUND = "wake_target_not_found"
    WEBHOOK_ACCESS_DENIED = "webhook_access_denied"
    WEBHOOK_NOT_FOUND = "webhook_not_found"
    WEBHOOK_SUBSCRIPTION_DISABLED = "webhook_subscription_disabled"

    def __str__(self) -> str:
        return str(self.value)
