# GENERATED by scripts/sync-sdk-python.sh from sdk/python/src/cove_sdk/_async/__init__.py by unasync — do not edit.
# The _async package is hand-written and async-first; the _sync package is generated from it by
# unasync (scripts/sync-sdk-python.sh). Code in _async never imports `asyncio` or `anyio`:
# `_colour.py` holds the colour-specific primitives.
