# GENERATED by scripts/sync-sdk-python.sh from sdk/python/src/cove_sdk/_async/_pagination.py by unasync — do not edit.
"""The one cursor loop behind every ``iter_*`` method (mirrored to the sync client by unasync).

TypeScript repeats this loop in each resource (``sdk/typescript/src/resources/vms.ts`` ``iter``);
here every list page has an items attribute and a ``next_cursor``, so one helper serves them all.
"""

from __future__ import annotations

from collections.abc import Iterator, Callable
from typing import Any


def paginate(
    fetch: Callable[[str | None], Any],
    items_attr: str,
    *,
    cursor: str | None = None,
) -> Iterator[Any]:
    """Yield every item of every page, fetching the next page only when the last is consumed.

    ``fetch(cursor)`` returns one page; the walk starts at ``cursor`` (``None`` = the first page)
    and ends when a page's ``next_cursor`` is ``None``, empty or unset. A per-call timeout given
    to ``fetch`` applies to each page, not to the walk.
    """
    while True:
        page = fetch(cursor)
        for item in getattr(page, items_attr):
            yield item
        # `or None` folds "" and the generated UNSET (falsy) into the end of the walk.
        cursor = getattr(page, "next_cursor", None) or None
        if cursor is None:
            return
