# GENERATED by scripts/sync-sdk-python.sh from sdk/python/src/cove_sdk/_async/_streams.py by unasync — do not edit.
"""Context-managed SSE streams: streamed exec, and the event streams with their reconnect loop.

Both are used as ``async with ... as stream: async for event in stream`` (sync: ``with`` /
``for``). Leaving the block -- an early ``break``, an exception, or the end of the stream --
closes the response, which is what stops the server holding an SSE task and a broadcast receiver
for a stream nobody reads. Iterating a stream outside its block raises :class:`CoveError`: a bare
generator would be closed only when the garbage collector got to it.

The request is sent on entering the block, so a non-2xx (raised by the transport's response hook
as its :class:`~cove_sdk.errors.CoveAPIError`) surfaces there. A transport failure mid-stream
raises :class:`~cove_sdk.errors.CoveConnectionError` (``CoveTimeoutError`` for an idle timeout).
Cancellation is never caught.
"""

from __future__ import annotations

import json
from collections.abc import Generator, Iterator, Callable, Mapping
from contextlib import AbstractContextManager
from types import TracebackType
from typing import Any, Generic, Protocol, Self, TypeVar

import httpx

from .._colour import sync_sleep, monotonic
from ..errors import (
    CoveConnectionError,
    CoveError,
    CoveTimeoutError,
    _parse_api_version,
)
from ..streams import (
    ExecError,
    ExecEvent,
    ExecExit,
    ExecPaused,
    ExecStderr,
    ExecStdout,
    LifecycleEvent,
    StreamLagged,
    VmEvent,
)
from ._sse import ServerSentEvent, iter_lines, parse_sse
from ._transport import CLIENT_DEFAULT, SyncCoveTransport, TimeoutArg, api_path

T = TypeVar("T")

RECONNECT_INTERVAL = 1.0
"""An event stream reconnects at most once per this many seconds."""

_NOT_ENTERED = "use the stream in a with block"


class _Sleep(Protocol):
    def __call__(self, seconds: float, /) -> None: ...


def _json(kind: str, data: str) -> Any:
    try:
        return json.loads(data)
    except ValueError:
        shown = data if len(data) <= 200 else data[:200] + "..."
        raise CoveError(f"malformed `{kind}` event: {shown}") from None


def _field(kind: str, payload: Any, name: str, typ: type) -> Any:
    value = payload.get(name) if isinstance(payload, dict) else None
    # bool is an int subclass, and never a valid exit code.
    if not isinstance(value, typ) or isinstance(value, bool):
        raise CoveError(f"malformed `{kind}` event: no {typ.__name__} `{name}`")
    return value


EXEC_ENCODING_HEADER = "x-cove-exec-encoding"
"""The header that confirms JSON-string ``stdout``/``stderr`` chunks on an exec response.

SSE ends a data line at a carriage return, so this SDK asks for the chunks JSON-encoded to carry
``\\r`` intact (``?encoding=json``, see ``EXEC_ENCODING_QUERY``), and decodes them when the
response confirms it; an older server ignores the request and sends raw chunks without it."""

EXEC_ENCODING_QUERY = "encoding"
"""The query parameter that asks an exec stream for JSON-string chunks. A query parameter, as in
the TypeScript SDK: a released server ignores one it does not know."""


def _json_chunks(response: httpx.Response) -> bool:
    encoding: str = response.headers.get(EXEC_ENCODING_HEADER, "")
    return encoding.strip().lower() == "json"


def _chunk(data: str, json_chunks: bool) -> str:
    """An output chunk: ``data`` JSON-decoded when the response said so, else as it came."""
    if not json_chunks:
        return data
    try:
        chunk = json.loads(data)
    except ValueError:
        return data
    return chunk if isinstance(chunk, str) else data


def _exec_event(sse: ServerSentEvent, json_chunks: bool) -> ExecEvent | None:
    kind = sse.event
    if kind == "stdout":
        return ExecStdout(_chunk(sse.data, json_chunks))
    if kind == "stderr":
        return ExecStderr(_chunk(sse.data, json_chunks))
    if kind == "exit":
        payload = _json(kind, sse.data)
        code = _field(kind, payload, "code", int)
        # A server older than `timed_out` leaves it out.
        return ExecExit(code, payload.get("timed_out") is True)
    if kind == "error":
        return ExecError(_field(kind, _json(kind, sse.data), "error", str))
    if kind == "paused":
        payload = _json(kind, sse.data)
        return ExecPaused(
            _field(kind, payload, "reason", str),
            _field(kind, payload, "new_state", str),
        )
    # An informational kind this SDK does not know: skipped, as in TypeScript.
    return None


def decode_console(sse: ServerSentEvent) -> str | None:
    """The console stream's one event type, ``console``: a raw console line."""
    return sse.data if sse.event == "console" else None


def decode_lifecycle(sse: ServerSentEvent) -> LifecycleEvent | None:
    """``lifecycle`` frames; the opening ``connected`` frame and unknown kinds are skipped."""
    if sse.event != "lifecycle":
        return None
    return LifecycleEvent(sse.id, _json(sse.event, sse.data))


def decode_vm_event(sse: ServerSentEvent) -> VmEvent:
    """Every frame of a VM event stream, by name (``connected``, ``vm-update``, ``state``, ...)."""
    return VmEvent(sse.event, _json(sse.event, sse.data))


def vm_stream_ended(event: VmEvent) -> bool:
    """Whether the server ends ``events.vm(name)``'s stream after ``event``: a ``state`` of
    ``deleted``, or an ``error`` (a failed create). The name is free again, and a later VM under
    it is a different VM, so the stream does not reconnect."""
    if event.kind == "error":
        return True
    data = event.data
    return (
        event.kind == "state"
        and isinstance(data, dict)
        and data.get("state") == "deleted"
    )


class _Stream:
    """One SSE response at a time, opened and closed explicitly."""

    def __init__(
        self,
        transport: SyncCoveTransport,
        method: str,
        path: str,
        *,
        params: Mapping[str, object] | None,
        body: object,
        timeout: TimeoutArg,
        headers: Mapping[str, str] | None = None,
    ) -> None:
        self._t = transport
        self._headers = headers
        self._method = method
        self._path = path
        self._params = params
        self._body = body
        self._timeout = timeout
        self._cm: AbstractContextManager[httpx.Response] | None = None
        self._response: httpx.Response | None = None
        self._entered = False
        self._inside = False  # between entering and leaving the with block
        self._events: Generator[Any, None] | None = None

    def _open(self) -> httpx.Response:
        cm = self._t.stream(
            self._method,
            self._path,
            params=self._params,
            json=self._body,
            timeout=self._timeout,
            headers=self._headers,
        )
        response = cm.__enter__()
        self._cm, self._response = cm, response
        return response

    def _close_response(self) -> None:
        cm, self._cm, self._response = self._cm, None, None
        if cm is not None:
            cm.__exit__(None, None, None)

    def _frames(self, response: httpx.Response) -> Generator[ServerSentEvent, None]:
        events = parse_sse(iter_lines(response.iter_bytes()))
        try:
            for sse in events:
                yield sse
        except httpx.TimeoutException as exc:
            raise CoveTimeoutError(f"stream timed out: {exc}") from exc
        except httpx.RequestError as exc:
            raise CoveConnectionError(f"stream failed: {exc}") from exc
        finally:
            events.close()

    def __enter__(self) -> Self:
        if self._entered:
            raise CoveError("a stream can be entered once")
        self._open()
        self._entered = self._inside = True
        return self

    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: TracebackType | None,
    ) -> None:
        self._inside = False
        events, self._events = self._events, None
        try:
            if events is not None:
                events.close()
        finally:
            self._close_response()

    def _check_entered(self) -> None:
        if not self._inside:
            raise CoveError(_NOT_ENTERED)
        if self._response is None:
            # Inside the block, but the stream ended without reconnecting.
            raise CoveError("the stream has ended; open a new one to read more")


class ExecStream(_Stream):
    """``vms.exec``'s stream: ``ExecStdout``/``ExecStderr`` chunks, then exactly one terminal
    ``ExecExit``/``ExecError``/``ExecPaused``, after which iteration stops."""

    def __init__(
        self,
        transport: SyncCoveTransport,
        path: str,
        *,
        body: Mapping[str, object],
        timeout: TimeoutArg = None,
        min_api_version: int | None = None,
    ) -> None:
        super().__init__(
            transport,
            "POST",
            path,
            params={EXEC_ENCODING_QUERY: "json"},
            body=dict(body),
            timeout=timeout,
        )
        self._min_api_version = min_api_version

    def _open(self) -> httpx.Response:
        if self._min_api_version is not None:
            self._require_api_version(self._min_api_version)
        return super()._open()

    def _require_api_version(self, minimum: int) -> None:
        """Refuse an exec with stdin unless the server says it speaks ``minimum`` or later: an
        older server ignores stdin and would run the command on empty input. ``/api/whoami`` is in
        the contract and served on every listener, and every successful reply carries
        ``x-cove-api-version``; read it from this reply, not the transport's last-seen version. A
        missing, zero or unreadable version, or a read that fails, is refused too."""
        try:
            response = self._t.request(
                "GET",
                api_path("/api/whoami"),
                timeout=CLIENT_DEFAULT if self._timeout is None else self._timeout,
            )
        except (CoveTimeoutError, CoveConnectionError):
            raise
        except CoveError as exc:
            raise CoveError(
                f"could not read the server's API version ({exc}), so cannot confirm it supports "
                f"exec stdin (API {minimum} or later); nothing was sent"
            ) from exc
        version = _parse_api_version(response.headers.get("x-cove-api-version"))
        if not version or version < minimum:
            raise CoveError(
                f"this server (API {'unknown' if version is None else version}) does not support "
                f"exec stdin; upgrade the server to API {minimum} or later. An older server would "
                "run the command without its input; nothing was sent"
            )

    def __iter__(self) -> Iterator[ExecEvent]:
        self._check_entered()
        if self._events is None:
            self._events = self._iterate()
        return self._events

    def _iterate(self) -> Generator[ExecEvent, None]:
        assert self._response is not None
        json_chunks = _json_chunks(self._response)
        frames = self._frames(self._response)
        try:
            for sse in frames:
                event = _exec_event(sse, json_chunks)
                if event is None:
                    continue
                yield event
                if isinstance(event, (ExecExit, ExecError, ExecPaused)):
                    return
        finally:
            frames.close()


class EventStream(Generic[T]):
    """An SSE event stream, decoded by ``decode`` (``None`` skips a frame); ``lagged`` frames
    become :class:`~cove_sdk.streams.StreamLagged`.

    With ``reconnect`` (the default for the event streams) a clean end of stream -- the server
    closes every event stream after 300 s -- opens a new one, at most once per second. The SDK
    sends no ``Last-Event-ID`` (the server does not honour one), so a reconnect starts from "now"
    and events between the close and the reconnect are lost. A non-2xx on a reconnect raises.

    ``terminal`` names an item after which the server ends the stream for good: the stream is
    closed and iteration stops there, without reconnecting.
    """

    def __init__(
        self,
        transport: SyncCoveTransport,
        path: str,
        *,
        decode: Callable[[ServerSentEvent], T | None],
        params: Mapping[str, object] | None = None,
        reconnect: bool = True,
        timeout: TimeoutArg = None,
        terminal: Callable[[T], bool] | None = None,
        _sleep: _Sleep = sync_sleep,
        _clock: Callable[[], float] = monotonic,
    ) -> None:
        self._stream = _Stream(
            transport, "GET", path, params=params, body=None, timeout=timeout
        )
        self._decode = decode
        self._reconnect = reconnect
        self._terminal = terminal
        self._sleep = _sleep
        self._clock = _clock
        self._connected_at = 0.0

    def __enter__(self) -> Self:
        self._stream.__enter__()
        self._connected_at = self._clock()
        return self

    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: TracebackType | None,
    ) -> None:
        self._stream.__exit__(exc_type, exc, tb)

    def __iter__(self) -> Iterator[T | StreamLagged]:
        s = self._stream
        s._check_entered()
        if s._events is None:
            s._events = self._iterate()
        events: Iterator[T | StreamLagged] = s._events
        return events

    def _iterate(self) -> Generator[T | StreamLagged, None]:
        s = self._stream
        ended = False
        while True:
            assert s._response is not None
            frames = s._frames(s._response)
            try:
                for sse in frames:
                    if sse.event == "lagged":
                        payload = _json(sse.event, sse.data)
                        yield StreamLagged(_field(sse.event, payload, "skipped", int))
                        continue
                    item = self._decode(sse)
                    if item is None:
                        continue
                    yield item
                    if self._terminal is not None and self._terminal(item):
                        ended = True
                        break
            finally:
                frames.close()
            s._close_response()
            if ended or not self._reconnect:
                return
            wait = self._connected_at + RECONNECT_INTERVAL - self._clock()
            if wait > 0:
                self._sleep(wait)
            s._open()
            self._connected_at = self._clock()


__all__ = [
    "RECONNECT_INTERVAL",
    "EventStream",
    "ExecStream",
    "decode_console",
    "decode_lifecycle",
    "decode_vm_event",
    "vm_stream_ended",
]
